# tools
required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/go-swagger/go-swagger/cmd/swagger",
]

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "0.11.5"

[[constraint]]
  branch = "master"
  name = "github.com/ejholmes/cloudwatch"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-version"

[[constraint]]
  branch = "master"
  name = "github.com/inconshreveable/go-update"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/stvp/rollbar"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.3.0"

[[override]]
  name = "cloud.google.com/go"
  version = "0.17.0"

[[constraint]]
  version = "1.20.0"
  name = "github.com/urfave/cli"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-5.0"

[[override]]
  name =  "github.com/juju/ratelimit"
  branch = "master"

[[constraint]]
  name = "github.com/appscode/go"

[[constraint]]
	name = "github.com/aws/aws-sdk-go"
  version = "~1.13.0"
  
[[constraint]]
  name =  "github.com/mholt/archiver"
