// Code generated by protoc-gen-go.
// source: services.proto
// DO NOT EDIT!

/*
Package controller is a generated protocol buffer package.

It is generated from these files:
	services.proto

It has these top-level messages:
	ListRequest
	ListResponse
	AppRequest
	AppListResponse
	AuthRequest
	AuthResponse
	CreateBuildRequest
	AppIdRequest
	BuildLogRequest
	BuildLogResponse
	EnvSetRequest
	ResourceListResponse
	AppListRequest
	BuildListResponse
	ProcessListResponse
	CreateResourceRequest
	AppResourceReq
	KubectlReq
	CmdResponse
	LogStreamReq
	ProcessRunReq
	ProcessRunResp
	StreamMsg
	ReleaseListResponse
	CreateReleaseRequest
	ListDomainReqponse
	CertificateReq
*/
package controller

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf2 "github.com/golang/protobuf/ptypes/duration"
import _ "github.com/gogo/protobuf/gogoproto"
import models "github.com/datacol-io/datacol/api/models"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRequest struct {
	Offset int32 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListResponse struct {
	Items []string `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListResponse) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

type AppRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	RepoUrl string `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl" json:"repo_url,omitempty"`
}

func (m *AppRequest) Reset()                    { *m = AppRequest{} }
func (m *AppRequest) String() string            { return proto.CompactTextString(m) }
func (*AppRequest) ProtoMessage()               {}
func (*AppRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppRequest) GetRepoUrl() string {
	if m != nil {
		return m.RepoUrl
	}
	return ""
}

type AppListResponse struct {
	Apps   []*models.App `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
	Limit  int32         `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset int32         `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *AppListResponse) Reset()                    { *m = AppListResponse{} }
func (m *AppListResponse) String() string            { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()               {}
func (*AppListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AppListResponse) GetApps() []*models.App {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *AppListResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AppListResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type AuthRequest struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Host     string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Project  string `protobuf:"bytes,3,opt,name=project" json:"project,omitempty"`
	Region   string `protobuf:"bytes,4,opt,name=region" json:"region,omitempty"`
	Provider string `protobuf:"bytes,5,opt,name=provider" json:"provider,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AuthResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AuthResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuthResponse) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *AuthResponse) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *AuthResponse) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type CreateBuildRequest struct {
	App       string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Procfile  []byte `protobuf:"bytes,3,opt,name=procfile,proto3" json:"procfile,omitempty"`
	Trigger   bool   `protobuf:"varint,4,opt,name=trigger" json:"trigger,omitempty"`
	DockerTag string `protobuf:"bytes,5,opt,name=docker_tag,json=dockerTag" json:"docker_tag,omitempty"`
}

func (m *CreateBuildRequest) Reset()                    { *m = CreateBuildRequest{} }
func (m *CreateBuildRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBuildRequest) ProtoMessage()               {}
func (*CreateBuildRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateBuildRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *CreateBuildRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CreateBuildRequest) GetProcfile() []byte {
	if m != nil {
		return m.Procfile
	}
	return nil
}

func (m *CreateBuildRequest) GetTrigger() bool {
	if m != nil {
		return m.Trigger
	}
	return false
}

func (m *CreateBuildRequest) GetDockerTag() string {
	if m != nil {
		return m.DockerTag
	}
	return ""
}

type AppIdRequest struct {
	App string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *AppIdRequest) Reset()                    { *m = AppIdRequest{} }
func (m *AppIdRequest) String() string            { return proto.CompactTextString(m) }
func (*AppIdRequest) ProtoMessage()               {}
func (*AppIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AppIdRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *AppIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BuildLogRequest struct {
	App string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Pos int32  `protobuf:"varint,3,opt,name=pos" json:"pos,omitempty"`
}

func (m *BuildLogRequest) Reset()                    { *m = BuildLogRequest{} }
func (m *BuildLogRequest) String() string            { return proto.CompactTextString(m) }
func (*BuildLogRequest) ProtoMessage()               {}
func (*BuildLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BuildLogRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *BuildLogRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BuildLogRequest) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type BuildLogResponse struct {
	Pos   int32    `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	Lines []string `protobuf:"bytes,2,rep,name=lines" json:"lines,omitempty"`
}

func (m *BuildLogResponse) Reset()                    { *m = BuildLogResponse{} }
func (m *BuildLogResponse) String() string            { return proto.CompactTextString(m) }
func (*BuildLogResponse) ProtoMessage()               {}
func (*BuildLogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BuildLogResponse) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *BuildLogResponse) GetLines() []string {
	if m != nil {
		return m.Lines
	}
	return nil
}

type EnvSetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *EnvSetRequest) Reset()                    { *m = EnvSetRequest{} }
func (m *EnvSetRequest) String() string            { return proto.CompactTextString(m) }
func (*EnvSetRequest) ProtoMessage()               {}
func (*EnvSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EnvSetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnvSetRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ResourceListResponse struct {
	Resources []*models.Resource `protobuf:"bytes,1,rep,name=resources" json:"resources,omitempty"`
}

func (m *ResourceListResponse) Reset()                    { *m = ResourceListResponse{} }
func (m *ResourceListResponse) String() string            { return proto.CompactTextString(m) }
func (*ResourceListResponse) ProtoMessage()               {}
func (*ResourceListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ResourceListResponse) GetResources() []*models.Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type AppListRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Limit int64  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *AppListRequest) Reset()                    { *m = AppListRequest{} }
func (m *AppListRequest) String() string            { return proto.CompactTextString(m) }
func (*AppListRequest) ProtoMessage()               {}
func (*AppListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AppListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type BuildListResponse struct {
	Builds []*models.Build `protobuf:"bytes,1,rep,name=builds" json:"builds,omitempty"`
}

func (m *BuildListResponse) Reset()                    { *m = BuildListResponse{} }
func (m *BuildListResponse) String() string            { return proto.CompactTextString(m) }
func (*BuildListResponse) ProtoMessage()               {}
func (*BuildListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *BuildListResponse) GetBuilds() []*models.Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

type ProcessListResponse struct {
	Items []*models.Process `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
}

func (m *ProcessListResponse) Reset()                    { *m = ProcessListResponse{} }
func (m *ProcessListResponse) String() string            { return proto.CompactTextString(m) }
func (*ProcessListResponse) ProtoMessage()               {}
func (*ProcessListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ProcessListResponse) GetItems() []*models.Process {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateResourceRequest struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Kind   string            `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Params map[string]string `protobuf:"bytes,3,rep,name=params" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CreateResourceRequest) Reset()                    { *m = CreateResourceRequest{} }
func (m *CreateResourceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateResourceRequest) ProtoMessage()               {}
func (*CreateResourceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CreateResourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateResourceRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *CreateResourceRequest) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type AppResourceReq struct {
	App      string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Resource string `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
}

func (m *AppResourceReq) Reset()                    { *m = AppResourceReq{} }
func (m *AppResourceReq) String() string            { return proto.CompactTextString(m) }
func (*AppResourceReq) ProtoMessage()               {}
func (*AppResourceReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *AppResourceReq) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *AppResourceReq) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type KubectlReq struct {
	Args []string `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
}

func (m *KubectlReq) Reset()                    { *m = KubectlReq{} }
func (m *KubectlReq) String() string            { return proto.CompactTextString(m) }
func (*KubectlReq) ProtoMessage()               {}
func (*KubectlReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *KubectlReq) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type CmdResponse struct {
	ExitCode int32  `protobuf:"varint,1,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	Err      string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	StdOut   string `protobuf:"bytes,3,opt,name=stdOut" json:"stdOut,omitempty"`
	StdErr   string `protobuf:"bytes,4,opt,name=stdErr" json:"stdErr,omitempty"`
}

func (m *CmdResponse) Reset()                    { *m = CmdResponse{} }
func (m *CmdResponse) String() string            { return proto.CompactTextString(m) }
func (*CmdResponse) ProtoMessage()               {}
func (*CmdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CmdResponse) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *CmdResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CmdResponse) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

func (m *CmdResponse) GetStdErr() string {
	if m != nil {
		return m.StdErr
	}
	return ""
}

type LogStreamReq struct {
	Name     string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Follow   bool                       `protobuf:"varint,2,opt,name=follow" json:"follow,omitempty"`
	Since    *google_protobuf2.Duration `protobuf:"bytes,3,opt,name=since" json:"since,omitempty"`
	Proctype string                     `protobuf:"bytes,4,opt,name=proctype" json:"proctype,omitempty"`
}

func (m *LogStreamReq) Reset()                    { *m = LogStreamReq{} }
func (m *LogStreamReq) String() string            { return proto.CompactTextString(m) }
func (*LogStreamReq) ProtoMessage()               {}
func (*LogStreamReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *LogStreamReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogStreamReq) GetFollow() bool {
	if m != nil {
		return m.Follow
	}
	return false
}

func (m *LogStreamReq) GetSince() *google_protobuf2.Duration {
	if m != nil {
		return m.Since
	}
	return nil
}

func (m *LogStreamReq) GetProctype() string {
	if m != nil {
		return m.Proctype
	}
	return ""
}

type ProcessRunReq struct {
	Name    string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Command []string `protobuf:"bytes,2,rep,name=command" json:"command,omitempty"`
}

func (m *ProcessRunReq) Reset()                    { *m = ProcessRunReq{} }
func (m *ProcessRunReq) String() string            { return proto.CompactTextString(m) }
func (*ProcessRunReq) ProtoMessage()               {}
func (*ProcessRunReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ProcessRunReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProcessRunReq) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

type ProcessRunResp struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *ProcessRunResp) Reset()                    { *m = ProcessRunResp{} }
func (m *ProcessRunResp) String() string            { return proto.CompactTextString(m) }
func (*ProcessRunResp) ProtoMessage()               {}
func (*ProcessRunResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ProcessRunResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProcessRunResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type StreamMsg struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *StreamMsg) Reset()                    { *m = StreamMsg{} }
func (m *StreamMsg) String() string            { return proto.CompactTextString(m) }
func (*StreamMsg) ProtoMessage()               {}
func (*StreamMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *StreamMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReleaseListResponse struct {
	Releases []*models.Release `protobuf:"bytes,1,rep,name=releases" json:"releases,omitempty"`
}

func (m *ReleaseListResponse) Reset()                    { *m = ReleaseListResponse{} }
func (m *ReleaseListResponse) String() string            { return proto.CompactTextString(m) }
func (*ReleaseListResponse) ProtoMessage()               {}
func (*ReleaseListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ReleaseListResponse) GetReleases() []*models.Release {
	if m != nil {
		return m.Releases
	}
	return nil
}

type CreateReleaseRequest struct {
	Build  *models.Build `protobuf:"bytes,1,opt,name=build" json:"build,omitempty"`
	Domain string        `protobuf:"bytes,2,opt,name=domain" json:"domain,omitempty"`
}

func (m *CreateReleaseRequest) Reset()                    { *m = CreateReleaseRequest{} }
func (m *CreateReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateReleaseRequest) ProtoMessage()               {}
func (*CreateReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *CreateReleaseRequest) GetBuild() *models.Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *CreateReleaseRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type ListDomainReqponse struct {
	Url []string `protobuf:"bytes,1,rep,name=url" json:"url,omitempty"`
}

func (m *ListDomainReqponse) Reset()                    { *m = ListDomainReqponse{} }
func (m *ListDomainReqponse) String() string            { return proto.CompactTextString(m) }
func (*ListDomainReqponse) ProtoMessage()               {}
func (*ListDomainReqponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ListDomainReqponse) GetUrl() []string {
	if m != nil {
		return m.Url
	}
	return nil
}

type CertificateReq struct {
	App         string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Domain      string `protobuf:"bytes,2,opt,name=domain" json:"domain,omitempty"`
	CertEncoded string `protobuf:"bytes,3,opt,name=cert_encoded,json=certEncoded" json:"cert_encoded,omitempty"`
	KeyEncoded  string `protobuf:"bytes,4,opt,name=key_encoded,json=keyEncoded" json:"key_encoded,omitempty"`
}

func (m *CertificateReq) Reset()                    { *m = CertificateReq{} }
func (m *CertificateReq) String() string            { return proto.CompactTextString(m) }
func (*CertificateReq) ProtoMessage()               {}
func (*CertificateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *CertificateReq) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *CertificateReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *CertificateReq) GetCertEncoded() string {
	if m != nil {
		return m.CertEncoded
	}
	return ""
}

func (m *CertificateReq) GetKeyEncoded() string {
	if m != nil {
		return m.KeyEncoded
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "controller.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "controller.ListResponse")
	proto.RegisterType((*AppRequest)(nil), "controller.AppRequest")
	proto.RegisterType((*AppListResponse)(nil), "controller.AppListResponse")
	proto.RegisterType((*AuthRequest)(nil), "controller.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "controller.AuthResponse")
	proto.RegisterType((*CreateBuildRequest)(nil), "controller.CreateBuildRequest")
	proto.RegisterType((*AppIdRequest)(nil), "controller.AppIdRequest")
	proto.RegisterType((*BuildLogRequest)(nil), "controller.BuildLogRequest")
	proto.RegisterType((*BuildLogResponse)(nil), "controller.BuildLogResponse")
	proto.RegisterType((*EnvSetRequest)(nil), "controller.EnvSetRequest")
	proto.RegisterType((*ResourceListResponse)(nil), "controller.ResourceListResponse")
	proto.RegisterType((*AppListRequest)(nil), "controller.AppListRequest")
	proto.RegisterType((*BuildListResponse)(nil), "controller.BuildListResponse")
	proto.RegisterType((*ProcessListResponse)(nil), "controller.ProcessListResponse")
	proto.RegisterType((*CreateResourceRequest)(nil), "controller.CreateResourceRequest")
	proto.RegisterType((*AppResourceReq)(nil), "controller.AppResourceReq")
	proto.RegisterType((*KubectlReq)(nil), "controller.KubectlReq")
	proto.RegisterType((*CmdResponse)(nil), "controller.CmdResponse")
	proto.RegisterType((*LogStreamReq)(nil), "controller.LogStreamReq")
	proto.RegisterType((*ProcessRunReq)(nil), "controller.ProcessRunReq")
	proto.RegisterType((*ProcessRunResp)(nil), "controller.ProcessRunResp")
	proto.RegisterType((*StreamMsg)(nil), "controller.StreamMsg")
	proto.RegisterType((*ReleaseListResponse)(nil), "controller.ReleaseListResponse")
	proto.RegisterType((*CreateReleaseRequest)(nil), "controller.CreateReleaseRequest")
	proto.RegisterType((*ListDomainReqponse)(nil), "controller.ListDomainReqponse")
	proto.RegisterType((*CertificateReq)(nil), "controller.CertificateReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProviderService service

type ProviderServiceClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Account api
	AppList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*AppListResponse, error)
	AppCreate(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error)
	AppGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error)
	AppRestart(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	AppDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Certificates API
	CertificateCreate(ctx context.Context, in *CertificateReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	CertificateDelete(ctx context.Context, in *CertificateReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Update Domain API
	AppUpdateDomain(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Build Api
	BuildCreate(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*models.Build, error)
	BuildUpload(ctx context.Context, opts ...grpc.CallOption) (ProviderService_BuildUploadClient, error)
	BuildRelease(ctx context.Context, in *CreateReleaseRequest, opts ...grpc.CallOption) (*models.Release, error)
	BuildGet(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*models.Build, error)
	BuildDelete(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	BuildList(ctx context.Context, in *AppListRequest, opts ...grpc.CallOption) (*BuildListResponse, error)
	BuildLogs(ctx context.Context, in *BuildLogRequest, opts ...grpc.CallOption) (*BuildLogResponse, error)
	EnvironmentGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.EnvConfig, error)
	EnvironmentSet(ctx context.Context, in *EnvSetRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Release endpoints
	ReleaseList(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*ReleaseListResponse, error)
	ReleaseDelete(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Resource endpoints
	ResourceList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ResourceListResponse, error)
	ResourceGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.Resource, error)
	ResourceCreate(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*models.Resource, error)
	ResourceDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ResourceLink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error)
	ResourceUnlink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error)
	// kubectl api wrappers
	Kubectl(ctx context.Context, in *KubectlReq, opts ...grpc.CallOption) (*CmdResponse, error)
	// Process api
	ProcessRun(ctx context.Context, in *ProcessRunReq, opts ...grpc.CallOption) (*ProcessRunResp, error)
	ProcessList(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*ProcessListResponse, error)
	ProcessSave(ctx context.Context, in *models.Formation, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ProcessLimits(ctx context.Context, in *models.ResourceLimits, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Logs API
	LogStream(ctx context.Context, in *LogStreamReq, opts ...grpc.CallOption) (ProviderService_LogStreamClient, error)
	// Docker Cred API
	DockerCredsGet(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*models.DockerCred, error)
}

type providerServiceClient struct {
	cc *grpc.ClientConn
}

func NewProviderServiceClient(cc *grpc.ClientConn) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppCreate(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error) {
	out := new(models.App)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error) {
	out := new(models.App)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppRestart(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppRestart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) CertificateCreate(ctx context.Context, in *CertificateReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/CertificateCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) CertificateDelete(ctx context.Context, in *CertificateReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/CertificateDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppUpdateDomain(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppUpdateDomain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildCreate(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*models.Build, error) {
	out := new(models.Build)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildUpload(ctx context.Context, opts ...grpc.CallOption) (ProviderService_BuildUploadClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ProviderService_serviceDesc.Streams[0], c.cc, "/controller.ProviderService/BuildUpload", opts...)
	if err != nil {
		return nil, err
	}
	x := &providerServiceBuildUploadClient{stream}
	return x, nil
}

type ProviderService_BuildUploadClient interface {
	Send(*StreamMsg) error
	CloseAndRecv() (*google_protobuf1.Empty, error)
	grpc.ClientStream
}

type providerServiceBuildUploadClient struct {
	grpc.ClientStream
}

func (x *providerServiceBuildUploadClient) Send(m *StreamMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *providerServiceBuildUploadClient) CloseAndRecv() (*google_protobuf1.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf1.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *providerServiceClient) BuildRelease(ctx context.Context, in *CreateReleaseRequest, opts ...grpc.CallOption) (*models.Release, error) {
	out := new(models.Release)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildGet(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*models.Build, error) {
	out := new(models.Build)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildDelete(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildList(ctx context.Context, in *AppListRequest, opts ...grpc.CallOption) (*BuildListResponse, error) {
	out := new(BuildListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildLogs(ctx context.Context, in *BuildLogRequest, opts ...grpc.CallOption) (*BuildLogResponse, error) {
	out := new(BuildLogResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) EnvironmentGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.EnvConfig, error) {
	out := new(models.EnvConfig)
	err := grpc.Invoke(ctx, "/controller.ProviderService/EnvironmentGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) EnvironmentSet(ctx context.Context, in *EnvSetRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/EnvironmentSet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ReleaseList(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*ReleaseListResponse, error) {
	out := new(ReleaseListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ReleaseList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ReleaseDelete(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ReleaseDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ResourceListResponse, error) {
	out := new(ResourceListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceCreate(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceLink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceLink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceUnlink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceUnlink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) Kubectl(ctx context.Context, in *KubectlReq, opts ...grpc.CallOption) (*CmdResponse, error) {
	out := new(CmdResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/Kubectl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProcessRun(ctx context.Context, in *ProcessRunReq, opts ...grpc.CallOption) (*ProcessRunResp, error) {
	out := new(ProcessRunResp)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ProcessRun", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProcessList(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*ProcessListResponse, error) {
	out := new(ProcessListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ProcessList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProcessSave(ctx context.Context, in *models.Formation, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ProcessSave", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProcessLimits(ctx context.Context, in *models.ResourceLimits, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ProcessLimits", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) LogStream(ctx context.Context, in *LogStreamReq, opts ...grpc.CallOption) (ProviderService_LogStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ProviderService_serviceDesc.Streams[1], c.cc, "/controller.ProviderService/LogStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &providerServiceLogStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProviderService_LogStreamClient interface {
	Recv() (*StreamMsg, error)
	grpc.ClientStream
}

type providerServiceLogStreamClient struct {
	grpc.ClientStream
}

func (x *providerServiceLogStreamClient) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *providerServiceClient) DockerCredsGet(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*models.DockerCred, error) {
	out := new(models.DockerCred)
	err := grpc.Invoke(ctx, "/controller.ProviderService/DockerCredsGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProviderService service

type ProviderServiceServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	// Account api
	AppList(context.Context, *ListRequest) (*AppListResponse, error)
	AppCreate(context.Context, *AppRequest) (*models.App, error)
	AppGet(context.Context, *AppRequest) (*models.App, error)
	AppRestart(context.Context, *AppRequest) (*google_protobuf1.Empty, error)
	AppDelete(context.Context, *AppRequest) (*google_protobuf1.Empty, error)
	// Certificates API
	CertificateCreate(context.Context, *CertificateReq) (*google_protobuf1.Empty, error)
	CertificateDelete(context.Context, *CertificateReq) (*google_protobuf1.Empty, error)
	// Update Domain API
	AppUpdateDomain(context.Context, *AppResourceReq) (*google_protobuf1.Empty, error)
	// Build Api
	BuildCreate(context.Context, *CreateBuildRequest) (*models.Build, error)
	BuildUpload(ProviderService_BuildUploadServer) error
	BuildRelease(context.Context, *CreateReleaseRequest) (*models.Release, error)
	BuildGet(context.Context, *AppIdRequest) (*models.Build, error)
	BuildDelete(context.Context, *AppIdRequest) (*google_protobuf1.Empty, error)
	BuildList(context.Context, *AppListRequest) (*BuildListResponse, error)
	BuildLogs(context.Context, *BuildLogRequest) (*BuildLogResponse, error)
	EnvironmentGet(context.Context, *AppRequest) (*models.EnvConfig, error)
	EnvironmentSet(context.Context, *EnvSetRequest) (*google_protobuf1.Empty, error)
	// Release endpoints
	ReleaseList(context.Context, *AppRequest) (*ReleaseListResponse, error)
	ReleaseDelete(context.Context, *AppIdRequest) (*google_protobuf1.Empty, error)
	// Resource endpoints
	ResourceList(context.Context, *ListRequest) (*ResourceListResponse, error)
	ResourceGet(context.Context, *AppRequest) (*models.Resource, error)
	ResourceCreate(context.Context, *CreateResourceRequest) (*models.Resource, error)
	ResourceDelete(context.Context, *AppRequest) (*google_protobuf1.Empty, error)
	ResourceLink(context.Context, *AppResourceReq) (*models.Resource, error)
	ResourceUnlink(context.Context, *AppResourceReq) (*models.Resource, error)
	// kubectl api wrappers
	Kubectl(context.Context, *KubectlReq) (*CmdResponse, error)
	// Process api
	ProcessRun(context.Context, *ProcessRunReq) (*ProcessRunResp, error)
	ProcessList(context.Context, *AppRequest) (*ProcessListResponse, error)
	ProcessSave(context.Context, *models.Formation) (*google_protobuf1.Empty, error)
	ProcessLimits(context.Context, *models.ResourceLimits) (*google_protobuf1.Empty, error)
	// Logs API
	LogStream(*LogStreamReq, ProviderService_LogStreamServer) error
	// Docker Cred API
	DockerCredsGet(context.Context, *google_protobuf1.Empty) (*models.DockerCred, error)
}

func RegisterProviderServiceServer(s *grpc.Server, srv ProviderServiceServer) {
	s.RegisterService(&_ProviderService_serviceDesc, srv)
}

func _ProviderService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppList(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppCreate(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppGet(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppRestart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppRestart(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppDelete(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_CertificateCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).CertificateCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/CertificateCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).CertificateCreate(ctx, req.(*CertificateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_CertificateDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).CertificateDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/CertificateDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).CertificateDelete(ctx, req.(*CertificateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppUpdateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppResourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppUpdateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppUpdateDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppUpdateDomain(ctx, req.(*AppResourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildCreate(ctx, req.(*CreateBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServiceServer).BuildUpload(&providerServiceBuildUploadServer{stream})
}

type ProviderService_BuildUploadServer interface {
	SendAndClose(*google_protobuf1.Empty) error
	Recv() (*StreamMsg, error)
	grpc.ServerStream
}

type providerServiceBuildUploadServer struct {
	grpc.ServerStream
}

func (x *providerServiceBuildUploadServer) SendAndClose(m *google_protobuf1.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *providerServiceBuildUploadServer) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProviderService_BuildRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildRelease(ctx, req.(*CreateReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildGet(ctx, req.(*AppIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildDelete(ctx, req.(*AppIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildList(ctx, req.(*AppListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildLogs(ctx, req.(*BuildLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_EnvironmentGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).EnvironmentGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/EnvironmentGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).EnvironmentGet(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_EnvironmentSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).EnvironmentSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/EnvironmentSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).EnvironmentSet(ctx, req.(*EnvSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ReleaseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ReleaseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ReleaseList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ReleaseList(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ReleaseDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ReleaseDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ReleaseDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ReleaseDelete(ctx, req.(*AppIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceList(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceGet(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceCreate(ctx, req.(*CreateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceDelete(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppResourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceLink(ctx, req.(*AppResourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceUnlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppResourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceUnlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceUnlink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceUnlink(ctx, req.(*AppResourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_Kubectl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubectlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Kubectl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/Kubectl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Kubectl(ctx, req.(*KubectlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProcessRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRunReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProcessRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ProcessRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProcessRun(ctx, req.(*ProcessRunReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProcessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProcessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ProcessList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProcessList(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProcessSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.Formation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProcessSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ProcessSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProcessSave(ctx, req.(*models.Formation))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProcessLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.ResourceLimits)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProcessLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ProcessLimits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProcessLimits(ctx, req.(*models.ResourceLimits))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_LogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogStreamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServiceServer).LogStream(m, &providerServiceLogStreamServer{stream})
}

type ProviderService_LogStreamServer interface {
	Send(*StreamMsg) error
	grpc.ServerStream
}

type providerServiceLogStreamServer struct {
	grpc.ServerStream
}

func (x *providerServiceLogStreamServer) Send(m *StreamMsg) error {
	return x.ServerStream.SendMsg(m)
}

func _ProviderService_DockerCredsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).DockerCredsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/DockerCredsGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).DockerCredsGet(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProviderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _ProviderService_Auth_Handler,
		},
		{
			MethodName: "AppList",
			Handler:    _ProviderService_AppList_Handler,
		},
		{
			MethodName: "AppCreate",
			Handler:    _ProviderService_AppCreate_Handler,
		},
		{
			MethodName: "AppGet",
			Handler:    _ProviderService_AppGet_Handler,
		},
		{
			MethodName: "AppRestart",
			Handler:    _ProviderService_AppRestart_Handler,
		},
		{
			MethodName: "AppDelete",
			Handler:    _ProviderService_AppDelete_Handler,
		},
		{
			MethodName: "CertificateCreate",
			Handler:    _ProviderService_CertificateCreate_Handler,
		},
		{
			MethodName: "CertificateDelete",
			Handler:    _ProviderService_CertificateDelete_Handler,
		},
		{
			MethodName: "AppUpdateDomain",
			Handler:    _ProviderService_AppUpdateDomain_Handler,
		},
		{
			MethodName: "BuildCreate",
			Handler:    _ProviderService_BuildCreate_Handler,
		},
		{
			MethodName: "BuildRelease",
			Handler:    _ProviderService_BuildRelease_Handler,
		},
		{
			MethodName: "BuildGet",
			Handler:    _ProviderService_BuildGet_Handler,
		},
		{
			MethodName: "BuildDelete",
			Handler:    _ProviderService_BuildDelete_Handler,
		},
		{
			MethodName: "BuildList",
			Handler:    _ProviderService_BuildList_Handler,
		},
		{
			MethodName: "BuildLogs",
			Handler:    _ProviderService_BuildLogs_Handler,
		},
		{
			MethodName: "EnvironmentGet",
			Handler:    _ProviderService_EnvironmentGet_Handler,
		},
		{
			MethodName: "EnvironmentSet",
			Handler:    _ProviderService_EnvironmentSet_Handler,
		},
		{
			MethodName: "ReleaseList",
			Handler:    _ProviderService_ReleaseList_Handler,
		},
		{
			MethodName: "ReleaseDelete",
			Handler:    _ProviderService_ReleaseDelete_Handler,
		},
		{
			MethodName: "ResourceList",
			Handler:    _ProviderService_ResourceList_Handler,
		},
		{
			MethodName: "ResourceGet",
			Handler:    _ProviderService_ResourceGet_Handler,
		},
		{
			MethodName: "ResourceCreate",
			Handler:    _ProviderService_ResourceCreate_Handler,
		},
		{
			MethodName: "ResourceDelete",
			Handler:    _ProviderService_ResourceDelete_Handler,
		},
		{
			MethodName: "ResourceLink",
			Handler:    _ProviderService_ResourceLink_Handler,
		},
		{
			MethodName: "ResourceUnlink",
			Handler:    _ProviderService_ResourceUnlink_Handler,
		},
		{
			MethodName: "Kubectl",
			Handler:    _ProviderService_Kubectl_Handler,
		},
		{
			MethodName: "ProcessRun",
			Handler:    _ProviderService_ProcessRun_Handler,
		},
		{
			MethodName: "ProcessList",
			Handler:    _ProviderService_ProcessList_Handler,
		},
		{
			MethodName: "ProcessSave",
			Handler:    _ProviderService_ProcessSave_Handler,
		},
		{
			MethodName: "ProcessLimits",
			Handler:    _ProviderService_ProcessLimits_Handler,
		},
		{
			MethodName: "DockerCredsGet",
			Handler:    _ProviderService_DockerCredsGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BuildUpload",
			Handler:       _ProviderService_BuildUpload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "LogStream",
			Handler:       _ProviderService_LogStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services.proto",
}

func init() { proto.RegisterFile("services.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1840 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x5b, 0x6f, 0x1c, 0x49,
	0x15, 0x66, 0x1c, 0xdf, 0xe6, 0xcc, 0x78, 0x6c, 0x97, 0x6f, 0xe3, 0x4e, 0x62, 0x7b, 0x6b, 0x09,
	0x04, 0xaf, 0x32, 0xb3, 0x04, 0x24, 0xc0, 0xbb, 0x20, 0x39, 0xce, 0x04, 0x45, 0x18, 0x36, 0xb4,
	0xd7, 0x04, 0xc8, 0x42, 0xb6, 0x3d, 0x5d, 0x9e, 0x34, 0xd3, 0xd3, 0x55, 0x5b, 0x5d, 0x3d, 0x8b,
	0x15, 0x85, 0x07, 0x84, 0xc4, 0x0f, 0x40, 0xfc, 0x20, 0xde, 0xf6, 0x11, 0x09, 0x9e, 0x11, 0x8a,
	0xf8, 0x21, 0xa8, 0xaa, 0x4e, 0xf5, 0x74, 0xcf, 0xc5, 0x09, 0xe1, 0x65, 0xd4, 0xa7, 0x2e, 0xdf,
	0xf9, 0xea, 0xd4, 0x77, 0x4e, 0x55, 0x0d, 0x34, 0x52, 0x26, 0x87, 0x51, 0x97, 0xa5, 0x2d, 0x21,
	0xb9, 0xe2, 0x04, 0xba, 0x3c, 0x51, 0x92, 0xc7, 0x31, 0x93, 0xde, 0xad, 0x1e, 0xe7, 0xbd, 0x98,
	0xb5, 0x03, 0x11, 0xb5, 0x83, 0x24, 0xe1, 0x2a, 0x50, 0x11, 0x4f, 0x70, 0xa4, 0xd7, 0x14, 0xea,
	0x4a, 0xb0, 0xb4, 0xcd, 0x06, 0x42, 0x5d, 0xd9, 0x5f, 0xec, 0xd9, 0xc3, 0x9e, 0x30, 0x93, 0x66,
	0x46, 0xfe, 0x81, 0xfd, 0xf7, 0x7a, 0x91, 0x7a, 0x91, 0x5d, 0xb4, 0xba, 0x7c, 0xd0, 0xee, 0xf1,
	0x1e, 0x6f, 0x9b, 0xe6, 0x8b, 0xec, 0xd2, 0x58, 0xc6, 0x30, 0x5f, 0x38, 0xfc, 0xbb, 0x85, 0xe1,
	0x61, 0xa0, 0x82, 0x2e, 0x8f, 0xef, 0x45, 0xdc, 0x7d, 0x1a, 0x76, 0x03, 0x1e, 0xb2, 0x38, 0x6d,
	0x1b, 0xb7, 0x76, 0x16, 0xfd, 0x08, 0x6a, 0xa7, 0x51, 0xaa, 0x7c, 0xf6, 0x45, 0xc6, 0x52, 0x45,
	0xb6, 0x61, 0x91, 0x5f, 0x5e, 0xa6, 0x4c, 0x35, 0x2b, 0x07, 0x95, 0xbb, 0x0b, 0x3e, 0x5a, 0x64,
	0x13, 0x16, 0xe2, 0x68, 0x10, 0xa9, 0xe6, 0x9c, 0x69, 0xb6, 0x06, 0xfd, 0x3a, 0xd4, 0xed, 0xe4,
	0x54, 0xf0, 0x24, 0x65, 0x7a, 0x54, 0xa4, 0xd8, 0x20, 0x6d, 0x56, 0x0e, 0x6e, 0xdc, 0xad, 0xfa,
	0xd6, 0xa0, 0x1f, 0x01, 0x1c, 0x0b, 0xe1, 0x3c, 0x10, 0x98, 0x4f, 0x82, 0x01, 0x33, 0xf8, 0x55,
	0xdf, 0x7c, 0x93, 0x5d, 0x58, 0x96, 0x4c, 0xf0, 0xe7, 0x99, 0x8c, 0x8d, 0x83, 0xaa, 0xbf, 0xa4,
	0xed, 0x73, 0x19, 0xd3, 0x4b, 0x58, 0x3d, 0x16, 0xa2, 0xe4, 0xe5, 0x0e, 0xcc, 0x07, 0x42, 0x58,
	0x27, 0xb5, 0xfb, 0xb5, 0x96, 0x5d, 0x55, 0xeb, 0x58, 0x88, 0x07, 0xf3, 0x5f, 0xfd, 0x6b, 0xff,
	0x6b, 0xbe, 0xe9, 0x9e, 0x4e, 0xb9, 0xb0, 0xc0, 0x1b, 0xc5, 0x05, 0xd2, 0x6f, 0x41, 0xed, 0x38,
	0x53, 0x2f, 0x1c, 0x4b, 0x0f, 0x96, 0x45, 0x90, 0xa6, 0x5f, 0x72, 0x19, 0x22, 0xd3, 0xdc, 0xa6,
	0x7f, 0xaa, 0x40, 0xdd, 0x8e, 0x45, 0x42, 0x04, 0xe6, 0x5f, 0xf0, 0x54, 0xb9, 0x25, 0xe9, 0xef,
	0x7c, 0x99, 0x73, 0x85, 0x65, 0x36, 0x61, 0x49, 0x48, 0xfe, 0x3b, 0xd6, 0xb5, 0xce, 0xab, 0xbe,
	0x33, 0x35, 0x2b, 0xc9, 0x7a, 0x11, 0x4f, 0x9a, 0xf3, 0xa6, 0x03, 0x2d, 0x43, 0x43, 0xf2, 0x61,
	0x14, 0x32, 0xd9, 0x5c, 0x40, 0x1a, 0x68, 0xd3, 0xbf, 0x56, 0x80, 0x9c, 0x48, 0x16, 0x28, 0xf6,
	0x20, 0x8b, 0xe2, 0xd0, 0x31, 0x5f, 0x83, 0x1b, 0x81, 0x10, 0xc8, 0x45, 0x7f, 0x6a, 0xb7, 0x43,
	0x26, 0x53, 0x8d, 0x8e, 0xc1, 0x45, 0x13, 0xe1, 0xbb, 0x97, 0x51, 0xcc, 0x0c, 0xa3, 0xba, 0x9f,
	0xdb, 0x7a, 0x96, 0x92, 0x51, 0xaf, 0xc7, 0xa4, 0xe1, 0xb4, 0xec, 0x3b, 0x93, 0xdc, 0x06, 0x08,
	0x79, 0xb7, 0xcf, 0xe4, 0x73, 0x15, 0xf4, 0x90, 0x56, 0xd5, 0xb6, 0x7c, 0x1a, 0xf4, 0xe8, 0x87,
	0x50, 0x3f, 0x16, 0xe2, 0xf1, 0x35, 0x84, 0x1a, 0x30, 0x17, 0x85, 0xc8, 0x65, 0x2e, 0x0a, 0x69,
	0x07, 0x56, 0xcd, 0x12, 0x4e, 0x79, 0xef, 0xad, 0x27, 0xe9, 0x11, 0x82, 0xa7, 0xb8, 0x8b, 0xfa,
	0x93, 0x1e, 0xc1, 0xda, 0x08, 0x06, 0xb7, 0x06, 0x47, 0x55, 0xf2, 0x51, 0x56, 0x16, 0x09, 0x4b,
	0x9b, 0x73, 0x56, 0xa3, 0xc6, 0xa0, 0xdf, 0x83, 0x95, 0x4e, 0x32, 0x3c, 0x63, 0xea, 0x3a, 0x99,
	0x12, 0x98, 0xd7, 0xd9, 0xe4, 0xf6, 0x54, 0x7f, 0xd3, 0x47, 0xb0, 0xe9, 0xb3, 0x94, 0x67, 0xb2,
	0xcb, 0x4a, 0x22, 0x6d, 0x41, 0x55, 0x62, 0xbb, 0x53, 0xea, 0x9a, 0x53, 0xaa, 0x9b, 0xe0, 0x8f,
	0x86, 0xd0, 0x23, 0x68, 0xe4, 0x3a, 0x9f, 0xcd, 0xa0, 0xa4, 0xe9, 0x1b, 0x2e, 0x0d, 0x8f, 0x60,
	0xdd, 0x2e, 0xbc, 0x9c, 0x25, 0x8b, 0x17, 0xba, 0xd1, 0x79, 0x5f, 0x71, 0xde, 0xad, 0x5a, 0xb0,
	0x93, 0x7e, 0x0c, 0x1b, 0x4f, 0x24, 0xef, 0xb2, 0x34, 0x1d, 0x9b, 0xbd, 0xf0, 0x38, 0xcf, 0xe4,
	0xda, 0xfd, 0x55, 0x37, 0x19, 0xc7, 0xfa, 0xb6, 0x97, 0xfe, 0xad, 0x02, 0x5b, 0x56, 0x83, 0xf9,
	0x9a, 0xae, 0x8f, 0x5f, 0x3f, 0x4a, 0xdc, 0x26, 0x9a, 0x6f, 0xd2, 0x81, 0x45, 0x11, 0xc8, 0x60,
	0xa0, 0x77, 0x52, 0x7b, 0xba, 0xd7, 0x1a, 0x55, 0xd6, 0xd6, 0x54, 0xe8, 0xd6, 0x13, 0x33, 0xbe,
	0x93, 0x28, 0x79, 0xe5, 0xe3, 0x64, 0xef, 0x07, 0x50, 0x2b, 0x34, 0xeb, 0x6d, 0xef, 0xb3, 0x2b,
	0x27, 0x9f, 0x3e, 0xbb, 0xd2, 0x91, 0x1b, 0x06, 0x71, 0xe6, 0x12, 0xd2, 0x1a, 0x47, 0x73, 0xdf,
	0xaf, 0xd0, 0x1f, 0x99, 0xc8, 0x17, 0x9c, 0x4c, 0x11, 0x9f, 0xa7, 0x0b, 0x94, 0x1d, 0x80, 0x00,
	0xb9, 0x4d, 0x0f, 0x00, 0x7e, 0x92, 0x5d, 0xb0, 0xae, 0x8a, 0xf5, 0x5c, 0x02, 0xf3, 0x81, 0xec,
	0xb9, 0x0a, 0x68, 0xbe, 0x69, 0x0c, 0xb5, 0x93, 0x41, 0x98, 0xc7, 0xf6, 0x26, 0x54, 0xd9, 0xef,
	0x23, 0xf5, 0xbc, 0xcb, 0x43, 0x86, 0xca, 0x5c, 0xd6, 0x0d, 0x27, 0x3c, 0x34, 0x82, 0x65, 0x52,
	0xa2, 0x13, 0xfd, 0xa9, 0x6b, 0x43, 0xaa, 0xc2, 0x4f, 0x32, 0x57, 0x34, 0xd0, 0xc2, 0xf6, 0x8e,
	0x94, 0xae, 0x66, 0x58, 0x8b, 0xfe, 0xb9, 0x02, 0xf5, 0x53, 0xde, 0x3b, 0x53, 0x92, 0x05, 0x03,
	0xa4, 0x34, 0xb1, 0x15, 0xdb, 0xb0, 0x78, 0xc9, 0xe3, 0x98, 0x7f, 0x69, 0x3c, 0x2d, 0xfb, 0x68,
	0x91, 0x36, 0x2c, 0xa4, 0x51, 0xd2, 0xb5, 0xe5, 0xa0, 0x76, 0x7f, 0xb7, 0x65, 0xcf, 0xb6, 0x96,
	0x3b, 0x7a, 0x5a, 0x0f, 0xf1, 0x8c, 0xf2, 0xed, 0x38, 0x57, 0x42, 0xf4, 0x91, 0x82, 0x3c, 0x72,
	0x9b, 0xfe, 0x10, 0x56, 0x9c, 0x5e, 0xb2, 0x64, 0x16, 0x93, 0x26, 0x2c, 0x75, 0xf9, 0x60, 0x10,
	0x18, 0x5d, 0xe8, 0x98, 0x39, 0x93, 0x7e, 0x0c, 0x8d, 0xe2, 0xf4, 0x54, 0xcc, 0x5a, 0x49, 0xaa,
	0x02, 0x95, 0xa5, 0x18, 0x33, 0xb4, 0xe8, 0x3e, 0x54, 0x6d, 0x08, 0x7e, 0x9a, 0xf6, 0xf2, 0xcc,
	0xad, 0x98, 0x22, 0x67, 0x33, 0xf7, 0x01, 0x6c, 0xf8, 0x2c, 0x66, 0x41, 0x5a, 0x4e, 0xdc, 0x0f,
	0xf4, 0x56, 0x9b, 0xe6, 0x09, 0xf1, 0xe3, 0x70, 0x3f, 0x1f, 0x40, 0xcf, 0x60, 0xd3, 0x69, 0xd4,
	0x76, 0xa1, 0xfa, 0xdf, 0x87, 0x05, 0x93, 0x5f, 0xc6, 0xe1, 0x44, 0xee, 0xd9, 0x3e, 0xcd, 0x3c,
	0xe4, 0x83, 0x20, 0x72, 0x65, 0x19, 0x2d, 0xfa, 0x0d, 0x20, 0x9a, 0xd1, 0x43, 0x63, 0xf9, 0xec,
	0x8b, 0xbc, 0x92, 0xe9, 0xe3, 0xd1, 0xea, 0x4a, 0x7f, 0xd2, 0x3f, 0x40, 0xe3, 0x84, 0x49, 0x15,
	0x5d, 0x46, 0x5d, 0xc3, 0x60, 0x9a, 0x70, 0x67, 0xf8, 0x20, 0xef, 0x41, 0xbd, 0xcb, 0xa4, 0x7a,
	0xce, 0x12, 0xad, 0xc2, 0x10, 0xa5, 0x55, 0xd3, 0x6d, 0x1d, 0xdb, 0x44, 0xf6, 0xa1, 0xd6, 0x67,
	0x57, 0xf9, 0x08, 0xbb, 0xb9, 0xd0, 0x67, 0x57, 0x38, 0xe0, 0xfe, 0x3f, 0x77, 0x60, 0xf5, 0x09,
	0x9e, 0x46, 0x67, 0xf6, 0x7a, 0x44, 0x7e, 0x06, 0xf3, 0xfa, 0x68, 0x24, 0x3b, 0xc5, 0x34, 0x2e,
	0x1c, 0xac, 0x5e, 0x73, 0xb2, 0xc3, 0x06, 0x9e, 0x6e, 0xfc, 0xf1, 0x1f, 0xff, 0xf9, 0xcb, 0xdc,
	0x0a, 0x5d, 0x6e, 0x0f, 0xbf, 0xdd, 0x0e, 0x32, 0xf5, 0xe2, 0xa8, 0x72, 0x48, 0x7e, 0x0e, 0x4b,
	0x58, 0x16, 0xcb, 0x90, 0x85, 0x42, 0xe9, 0xdd, 0x2c, 0x41, 0x96, 0x2f, 0x0b, 0x74, 0xcd, 0xa0,
	0x02, 0xb1, 0xa8, 0xfa, 0x5e, 0xd0, 0x81, 0xea, 0xb1, 0x10, 0x76, 0xdb, 0xc8, 0xf6, 0xd8, 0x5c,
	0x87, 0x59, 0xbc, 0x55, 0x8c, 0x31, 0x13, 0x22, 0xd5, 0xcc, 0x1e, 0xc1, 0xe2, 0xb1, 0x10, 0x3f,
	0x66, 0xea, 0xed, 0x30, 0x76, 0x0c, 0xc6, 0x3a, 0x59, 0x75, 0x18, 0xed, 0x97, 0x5a, 0xbe, 0xaf,
	0xc8, 0x6f, 0xf0, 0x76, 0x94, 0xaa, 0x40, 0xce, 0xc6, 0xda, 0x9e, 0x48, 0xc4, 0x8e, 0xbe, 0x49,
	0xd2, 0x7d, 0x03, 0xbb, 0x4b, 0x76, 0xc6, 0x60, 0xdb, 0x12, 0x01, 0x3f, 0x35, 0xab, 0x7d, 0xc8,
	0x62, 0x76, 0xcd, 0x6a, 0x67, 0xa1, 0x23, 0xe9, 0xc3, 0x09, 0xd2, 0x9f, 0xc3, 0x7a, 0x41, 0x7a,
	0x18, 0x4b, 0xaf, 0x54, 0xba, 0x4b, 0xca, 0x7c, 0x93, 0x07, 0x6a, 0x3c, 0x68, 0xf5, 0xa5, 0xed,
	0x97, 0x81, 0x10, 0xe3, 0x1e, 0x90, 0xff, 0xff, 0xe1, 0xe1, 0x70, 0x8a, 0x07, 0x7d, 0xb3, 0x3c,
	0x17, 0xa1, 0xc6, 0xb7, 0x59, 0xe1, 0x4d, 0xc4, 0x27, 0x3f, 0x14, 0x66, 0xe2, 0xef, 0x1a, 0xfc,
	0x0d, 0x6f, 0x5d, 0xe3, 0xdb, 0xec, 0x72, 0x1e, 0x9e, 0x40, 0xcd, 0x24, 0x3c, 0xc6, 0x67, 0x6f,
	0xf2, 0x68, 0x2b, 0xde, 0xdc, 0xbc, 0x72, 0x95, 0xa0, 0xc4, 0x00, 0xd7, 0x29, 0x68, 0x60, 0x7b,
	0x5a, 0x93, 0x5f, 0x21, 0xe2, 0xb9, 0x88, 0x79, 0x10, 0x92, 0xad, 0x22, 0x62, 0x5e, 0xed, 0xde,
	0x44, 0x95, 0xae, 0x8f, 0x10, 0xdb, 0x99, 0x41, 0xba, 0x5b, 0x21, 0x4f, 0xa1, 0x8e, 0x6c, 0x4c,
	0x25, 0x23, 0x07, 0xd3, 0x0e, 0xe2, 0x62, 0x91, 0xf3, 0xc6, 0xeb, 0x22, 0xdd, 0x34, 0xf8, 0x0d,
	0x5a, 0xd7, 0xf8, 0xae, 0x46, 0x92, 0x53, 0x58, 0x36, 0xc0, 0x3a, 0x55, 0x9a, 0x63, 0x01, 0x7e,
	0x3c, 0x6b, 0xf1, 0xa5, 0x74, 0x41, 0xaa, 0x2f, 0xa3, 0xf0, 0x15, 0xf9, 0x25, 0x46, 0x00, 0x15,
	0x31, 0x1b, 0xf0, 0xad, 0xf4, 0x50, 0x44, 0x0e, 0xa0, 0x9a, 0xdf, 0xa2, 0x26, 0x94, 0x50, 0xac,
	0x37, 0xb7, 0x8b, 0x7d, 0x13, 0x17, 0x2f, 0x17, 0x65, 0x52, 0x8c, 0x32, 0xa6, 0x4d, 0xe8, 0x5c,
	0xf0, 0x5e, 0x4a, 0x6e, 0x4e, 0xc2, 0xe4, 0xf7, 0x5f, 0xef, 0xd6, 0xf4, 0x4e, 0x74, 0x71, 0xcb,
	0xb8, 0xd8, 0x26, 0x9b, 0x63, 0x6b, 0x68, 0xc7, 0x1a, 0xf8, 0x0c, 0x1a, 0x9d, 0x64, 0x18, 0x49,
	0x9e, 0x0c, 0x58, 0xa2, 0xae, 0xab, 0x50, 0xeb, 0x2e, 0xe8, 0x9d, 0x64, 0x78, 0xc2, 0x93, 0xcb,
	0xa8, 0x47, 0xb7, 0x0d, 0xf4, 0x1a, 0x69, 0x68, 0x68, 0x96, 0x0c, 0x1d, 0xf5, 0x67, 0x25, 0xd0,
	0x33, 0xa6, 0xc8, 0x6e, 0x11, 0xb4, 0x74, 0x79, 0x9e, 0x19, 0x7b, 0x04, 0xa7, 0xe3, 0xe0, 0x5d,
	0xa8, 0x15, 0x8e, 0xe2, 0x99, 0x74, 0xf7, 0x8b, 0xed, 0x53, 0xce, 0x6e, 0x7a, 0xd3, 0xe0, 0x6f,
	0x91, 0x8d, 0xa2, 0x00, 0x9d, 0x93, 0x0b, 0x58, 0xc1, 0x39, 0xef, 0xac, 0x1d, 0xac, 0xb6, 0x87,
	0x3b, 0x65, 0x7c, 0x9d, 0xec, 0x56, 0x43, 0x9f, 0x43, 0xbd, 0xf8, 0x1a, 0x98, 0x7d, 0x66, 0x1d,
	0x94, 0x97, 0x32, 0xf9, 0x80, 0xa0, 0x5b, 0xc6, 0xd7, 0x2a, 0x59, 0xb1, 0xbe, 0xf0, 0x9d, 0x40,
	0xce, 0x75, 0xa8, 0xac, 0x71, 0xdd, 0xce, 0x4e, 0xbc, 0x35, 0xca, 0x9a, 0xc9, 0xf1, 0x5c, 0x70,
	0x3e, 0x83, 0x86, 0x1b, 0x89, 0xd5, 0xea, 0xbd, 0x37, 0x5e, 0xc4, 0xa7, 0x38, 0x41, 0xd2, 0x74,
	0x8c, 0xf4, 0x6f, 0x47, 0xe8, 0xef, 0x78, 0x12, 0x21, 0xfb, 0xc3, 0xe9, 0xec, 0xa3, 0x62, 0xd8,
	0x93, 0xfe, 0xb5, 0x75, 0x7c, 0x92, 0xf4, 0x07, 0x06, 0xfb, 0x8e, 0xf7, 0xfe, 0x18, 0xb6, 0xd9,
	0xd6, 0x38, 0x4a, 0xfa, 0xed, 0x97, 0xae, 0xf5, 0x15, 0x19, 0x8c, 0x96, 0x72, 0x9e, 0xc4, 0xff,
	0xbb, 0xb3, 0x7b, 0xc6, 0xd9, 0x37, 0xbd, 0x3b, 0xd3, 0x9c, 0x65, 0xc9, 0xb8, 0xbb, 0x4f, 0x60,
	0x09, 0x1f, 0x17, 0xe5, 0x90, 0x8d, 0x5e, 0x1c, 0x5e, 0x49, 0x63, 0x85, 0x77, 0x86, 0xbb, 0xb6,
	0x90, 0x9a, 0x76, 0xd5, 0x47, 0x94, 0xcf, 0x00, 0x46, 0x97, 0xea, 0x72, 0x0e, 0x97, 0xee, 0xea,
	0x9e, 0x37, 0xab, 0x2b, 0x1d, 0xbb, 0xcc, 0x08, 0xdb, 0xd7, 0x96, 0x59, 0x42, 0x9e, 0x41, 0xad,
	0xf0, 0x9a, 0x7c, 0xbb, 0x44, 0x9e, 0xf2, 0xfc, 0x2c, 0x53, 0x47, 0x07, 0xe4, 0x69, 0x0e, 0x7e,
	0x16, 0x0c, 0x19, 0xc9, 0x8b, 0xd7, 0x23, 0x2e, 0x07, 0xe6, 0x4d, 0x32, 0x53, 0x3d, 0xb7, 0x0d,
	0xdc, 0x0e, 0xd9, 0x2a, 0xf2, 0xbd, 0x74, 0xd3, 0xc8, 0xb3, 0xfc, 0x9d, 0x72, 0xaa, 0xdf, 0xd3,
	0x29, 0xd9, 0x1e, 0xdf, 0x36, 0xdb, 0x3e, 0x13, 0xdf, 0x33, 0xf8, 0x9b, 0x1e, 0x29, 0xe2, 0xc7,
	0x16, 0xeb, 0x29, 0x54, 0xf3, 0xd7, 0x58, 0xb9, 0xe4, 0x14, 0x1f, 0x69, 0xde, 0xf4, 0xa3, 0xbc,
	0x1c, 0x69, 0x5d, 0xdd, 0x51, 0xf2, 0x1f, 0x56, 0xc8, 0x2f, 0xa0, 0xf1, 0xd0, 0xfc, 0xe9, 0x72,
	0x22, 0x59, 0x98, 0xda, 0x62, 0x30, 0x95, 0x9e, 0x47, 0xdc, 0x72, 0x46, 0xe3, 0x69, 0xd3, 0x00,
	0x13, 0xb2, 0x66, 0xaf, 0x2d, 0xba, 0x5d, 0xe3, 0x47, 0xc9, 0x83, 0xe6, 0x57, 0xaf, 0xf7, 0x2a,
	0x7f, 0x7f, 0xbd, 0x57, 0xf9, 0xf7, 0xeb, 0xbd, 0xca, 0xaf, 0x0b, 0x7f, 0x74, 0x5e, 0x2c, 0x1a,
	0xdc, 0xef, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0xac, 0x34, 0xfd, 0xf4, 0x0d, 0x15, 0x00, 0x00,
}
