// Code generated by protoc-gen-go.
// source: services.proto
// DO NOT EDIT!

/*
Package controller is a generated protocol buffer package.

It is generated from these files:
	services.proto

It has these top-level messages:
	ListRequest
	ListResponse
	AppRequest
	AppListResponse
	AuthRequest
	AuthResponse
	CreateBuildRequest
	AppIdRequest
	BuildLogRequest
	BuildLogResponse
	EnvSetRequest
	ResourceListResponse
	AppListRequest
	BuildListResponse
	ProcessListResponse
	CreateResourceRequest
	AppResourceReq
	KubectlReq
	CmdResponse
	LogStreamReq
	ProcessRunReq
	StreamMsg
	ReleaseListResponse
	CreateReleaseRequest
	ListDomainReqponse
	CertificateReq
*/
package controller

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf2 "github.com/golang/protobuf/ptypes/duration"
import _ "github.com/gogo/protobuf/gogoproto"
import models "github.com/datacol-io/datacol/api/models"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRequest struct {
	Offset int32 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListResponse struct {
	Items []string `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListResponse) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

type AppRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	RepoUrl string `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl" json:"repo_url,omitempty"`
}

func (m *AppRequest) Reset()                    { *m = AppRequest{} }
func (m *AppRequest) String() string            { return proto.CompactTextString(m) }
func (*AppRequest) ProtoMessage()               {}
func (*AppRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppRequest) GetRepoUrl() string {
	if m != nil {
		return m.RepoUrl
	}
	return ""
}

type AppListResponse struct {
	Apps   []*models.App `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
	Limit  int32         `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset int32         `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *AppListResponse) Reset()                    { *m = AppListResponse{} }
func (m *AppListResponse) String() string            { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()               {}
func (*AppListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AppListResponse) GetApps() []*models.App {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *AppListResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AppListResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type AuthRequest struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Host     string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Project  string `protobuf:"bytes,3,opt,name=project" json:"project,omitempty"`
	Region   string `protobuf:"bytes,4,opt,name=region" json:"region,omitempty"`
	Provider string `protobuf:"bytes,5,opt,name=provider" json:"provider,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AuthResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AuthResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuthResponse) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *AuthResponse) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *AuthResponse) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type CreateBuildRequest struct {
	App      string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Version  string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Procfile []byte `protobuf:"bytes,3,opt,name=procfile,proto3" json:"procfile,omitempty"`
}

func (m *CreateBuildRequest) Reset()                    { *m = CreateBuildRequest{} }
func (m *CreateBuildRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBuildRequest) ProtoMessage()               {}
func (*CreateBuildRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateBuildRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *CreateBuildRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CreateBuildRequest) GetProcfile() []byte {
	if m != nil {
		return m.Procfile
	}
	return nil
}

type AppIdRequest struct {
	App string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *AppIdRequest) Reset()                    { *m = AppIdRequest{} }
func (m *AppIdRequest) String() string            { return proto.CompactTextString(m) }
func (*AppIdRequest) ProtoMessage()               {}
func (*AppIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AppIdRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *AppIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BuildLogRequest struct {
	App string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Pos int32  `protobuf:"varint,3,opt,name=pos" json:"pos,omitempty"`
}

func (m *BuildLogRequest) Reset()                    { *m = BuildLogRequest{} }
func (m *BuildLogRequest) String() string            { return proto.CompactTextString(m) }
func (*BuildLogRequest) ProtoMessage()               {}
func (*BuildLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BuildLogRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *BuildLogRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BuildLogRequest) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type BuildLogResponse struct {
	Pos   int32    `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	Lines []string `protobuf:"bytes,2,rep,name=lines" json:"lines,omitempty"`
}

func (m *BuildLogResponse) Reset()                    { *m = BuildLogResponse{} }
func (m *BuildLogResponse) String() string            { return proto.CompactTextString(m) }
func (*BuildLogResponse) ProtoMessage()               {}
func (*BuildLogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BuildLogResponse) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *BuildLogResponse) GetLines() []string {
	if m != nil {
		return m.Lines
	}
	return nil
}

type EnvSetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *EnvSetRequest) Reset()                    { *m = EnvSetRequest{} }
func (m *EnvSetRequest) String() string            { return proto.CompactTextString(m) }
func (*EnvSetRequest) ProtoMessage()               {}
func (*EnvSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EnvSetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnvSetRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ResourceListResponse struct {
	Resources []*models.Resource `protobuf:"bytes,1,rep,name=resources" json:"resources,omitempty"`
}

func (m *ResourceListResponse) Reset()                    { *m = ResourceListResponse{} }
func (m *ResourceListResponse) String() string            { return proto.CompactTextString(m) }
func (*ResourceListResponse) ProtoMessage()               {}
func (*ResourceListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ResourceListResponse) GetResources() []*models.Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type AppListRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Limit int32  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *AppListRequest) Reset()                    { *m = AppListRequest{} }
func (m *AppListRequest) String() string            { return proto.CompactTextString(m) }
func (*AppListRequest) ProtoMessage()               {}
func (*AppListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AppListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type BuildListResponse struct {
	Builds []*models.Build `protobuf:"bytes,1,rep,name=builds" json:"builds,omitempty"`
}

func (m *BuildListResponse) Reset()                    { *m = BuildListResponse{} }
func (m *BuildListResponse) String() string            { return proto.CompactTextString(m) }
func (*BuildListResponse) ProtoMessage()               {}
func (*BuildListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *BuildListResponse) GetBuilds() []*models.Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

type ProcessListResponse struct {
	Items []*models.Process `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
}

func (m *ProcessListResponse) Reset()                    { *m = ProcessListResponse{} }
func (m *ProcessListResponse) String() string            { return proto.CompactTextString(m) }
func (*ProcessListResponse) ProtoMessage()               {}
func (*ProcessListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ProcessListResponse) GetItems() []*models.Process {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateResourceRequest struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Kind   string            `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Params map[string]string `protobuf:"bytes,3,rep,name=params" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CreateResourceRequest) Reset()                    { *m = CreateResourceRequest{} }
func (m *CreateResourceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateResourceRequest) ProtoMessage()               {}
func (*CreateResourceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CreateResourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateResourceRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *CreateResourceRequest) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type AppResourceReq struct {
	App      string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Resource string `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
}

func (m *AppResourceReq) Reset()                    { *m = AppResourceReq{} }
func (m *AppResourceReq) String() string            { return proto.CompactTextString(m) }
func (*AppResourceReq) ProtoMessage()               {}
func (*AppResourceReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *AppResourceReq) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *AppResourceReq) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type KubectlReq struct {
	Args []string `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
}

func (m *KubectlReq) Reset()                    { *m = KubectlReq{} }
func (m *KubectlReq) String() string            { return proto.CompactTextString(m) }
func (*KubectlReq) ProtoMessage()               {}
func (*KubectlReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *KubectlReq) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type CmdResponse struct {
	ExitCode int32  `protobuf:"varint,1,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	Err      string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	StdOut   string `protobuf:"bytes,3,opt,name=stdOut" json:"stdOut,omitempty"`
	StdErr   string `protobuf:"bytes,4,opt,name=stdErr" json:"stdErr,omitempty"`
}

func (m *CmdResponse) Reset()                    { *m = CmdResponse{} }
func (m *CmdResponse) String() string            { return proto.CompactTextString(m) }
func (*CmdResponse) ProtoMessage()               {}
func (*CmdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CmdResponse) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *CmdResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CmdResponse) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

func (m *CmdResponse) GetStdErr() string {
	if m != nil {
		return m.StdErr
	}
	return ""
}

type LogStreamReq struct {
	Name     string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Follow   bool                       `protobuf:"varint,2,opt,name=follow" json:"follow,omitempty"`
	Since    *google_protobuf2.Duration `protobuf:"bytes,3,opt,name=since" json:"since,omitempty"`
	Proctype string                     `protobuf:"bytes,4,opt,name=proctype" json:"proctype,omitempty"`
}

func (m *LogStreamReq) Reset()                    { *m = LogStreamReq{} }
func (m *LogStreamReq) String() string            { return proto.CompactTextString(m) }
func (*LogStreamReq) ProtoMessage()               {}
func (*LogStreamReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *LogStreamReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogStreamReq) GetFollow() bool {
	if m != nil {
		return m.Follow
	}
	return false
}

func (m *LogStreamReq) GetSince() *google_protobuf2.Duration {
	if m != nil {
		return m.Since
	}
	return nil
}

func (m *LogStreamReq) GetProctype() string {
	if m != nil {
		return m.Proctype
	}
	return ""
}

type ProcessRunReq struct {
	Name    string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Command []string `protobuf:"bytes,2,rep,name=command" json:"command,omitempty"`
}

func (m *ProcessRunReq) Reset()                    { *m = ProcessRunReq{} }
func (m *ProcessRunReq) String() string            { return proto.CompactTextString(m) }
func (*ProcessRunReq) ProtoMessage()               {}
func (*ProcessRunReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ProcessRunReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProcessRunReq) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

type StreamMsg struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *StreamMsg) Reset()                    { *m = StreamMsg{} }
func (m *StreamMsg) String() string            { return proto.CompactTextString(m) }
func (*StreamMsg) ProtoMessage()               {}
func (*StreamMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *StreamMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReleaseListResponse struct {
	Releases []*models.Release `protobuf:"bytes,1,rep,name=releases" json:"releases,omitempty"`
}

func (m *ReleaseListResponse) Reset()                    { *m = ReleaseListResponse{} }
func (m *ReleaseListResponse) String() string            { return proto.CompactTextString(m) }
func (*ReleaseListResponse) ProtoMessage()               {}
func (*ReleaseListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ReleaseListResponse) GetReleases() []*models.Release {
	if m != nil {
		return m.Releases
	}
	return nil
}

type CreateReleaseRequest struct {
	Build  *models.Build `protobuf:"bytes,1,opt,name=build" json:"build,omitempty"`
	Domain string        `protobuf:"bytes,2,opt,name=domain" json:"domain,omitempty"`
}

func (m *CreateReleaseRequest) Reset()                    { *m = CreateReleaseRequest{} }
func (m *CreateReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateReleaseRequest) ProtoMessage()               {}
func (*CreateReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *CreateReleaseRequest) GetBuild() *models.Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *CreateReleaseRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type ListDomainReqponse struct {
	Url []string `protobuf:"bytes,1,rep,name=url" json:"url,omitempty"`
}

func (m *ListDomainReqponse) Reset()                    { *m = ListDomainReqponse{} }
func (m *ListDomainReqponse) String() string            { return proto.CompactTextString(m) }
func (*ListDomainReqponse) ProtoMessage()               {}
func (*ListDomainReqponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ListDomainReqponse) GetUrl() []string {
	if m != nil {
		return m.Url
	}
	return nil
}

type CertificateReq struct {
	App         string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Domain      string `protobuf:"bytes,2,opt,name=domain" json:"domain,omitempty"`
	CertEncoded string `protobuf:"bytes,3,opt,name=cert_encoded,json=certEncoded" json:"cert_encoded,omitempty"`
	KeyEncoded  string `protobuf:"bytes,4,opt,name=key_encoded,json=keyEncoded" json:"key_encoded,omitempty"`
}

func (m *CertificateReq) Reset()                    { *m = CertificateReq{} }
func (m *CertificateReq) String() string            { return proto.CompactTextString(m) }
func (*CertificateReq) ProtoMessage()               {}
func (*CertificateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *CertificateReq) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *CertificateReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *CertificateReq) GetCertEncoded() string {
	if m != nil {
		return m.CertEncoded
	}
	return ""
}

func (m *CertificateReq) GetKeyEncoded() string {
	if m != nil {
		return m.KeyEncoded
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "controller.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "controller.ListResponse")
	proto.RegisterType((*AppRequest)(nil), "controller.AppRequest")
	proto.RegisterType((*AppListResponse)(nil), "controller.AppListResponse")
	proto.RegisterType((*AuthRequest)(nil), "controller.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "controller.AuthResponse")
	proto.RegisterType((*CreateBuildRequest)(nil), "controller.CreateBuildRequest")
	proto.RegisterType((*AppIdRequest)(nil), "controller.AppIdRequest")
	proto.RegisterType((*BuildLogRequest)(nil), "controller.BuildLogRequest")
	proto.RegisterType((*BuildLogResponse)(nil), "controller.BuildLogResponse")
	proto.RegisterType((*EnvSetRequest)(nil), "controller.EnvSetRequest")
	proto.RegisterType((*ResourceListResponse)(nil), "controller.ResourceListResponse")
	proto.RegisterType((*AppListRequest)(nil), "controller.AppListRequest")
	proto.RegisterType((*BuildListResponse)(nil), "controller.BuildListResponse")
	proto.RegisterType((*ProcessListResponse)(nil), "controller.ProcessListResponse")
	proto.RegisterType((*CreateResourceRequest)(nil), "controller.CreateResourceRequest")
	proto.RegisterType((*AppResourceReq)(nil), "controller.AppResourceReq")
	proto.RegisterType((*KubectlReq)(nil), "controller.KubectlReq")
	proto.RegisterType((*CmdResponse)(nil), "controller.CmdResponse")
	proto.RegisterType((*LogStreamReq)(nil), "controller.LogStreamReq")
	proto.RegisterType((*ProcessRunReq)(nil), "controller.ProcessRunReq")
	proto.RegisterType((*StreamMsg)(nil), "controller.StreamMsg")
	proto.RegisterType((*ReleaseListResponse)(nil), "controller.ReleaseListResponse")
	proto.RegisterType((*CreateReleaseRequest)(nil), "controller.CreateReleaseRequest")
	proto.RegisterType((*ListDomainReqponse)(nil), "controller.ListDomainReqponse")
	proto.RegisterType((*CertificateReq)(nil), "controller.CertificateReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProviderService service

type ProviderServiceClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Account api
	AppList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*AppListResponse, error)
	AppCreate(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error)
	AppGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error)
	AppRestart(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	AppDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Certificates API
	CertificateCreate(ctx context.Context, in *CertificateReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	CertificateDelete(ctx context.Context, in *CertificateReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Update Domain API
	AppUpdateDomain(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Build Api
	BuildCreate(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*models.Build, error)
	BuildImport(ctx context.Context, opts ...grpc.CallOption) (ProviderService_BuildImportClient, error)
	BuildRelease(ctx context.Context, in *CreateReleaseRequest, opts ...grpc.CallOption) (*models.Release, error)
	BuildGet(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*models.Build, error)
	BuildDelete(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	BuildList(ctx context.Context, in *AppListRequest, opts ...grpc.CallOption) (*BuildListResponse, error)
	BuildLogs(ctx context.Context, in *BuildLogRequest, opts ...grpc.CallOption) (*BuildLogResponse, error)
	EnvironmentGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.EnvConfig, error)
	EnvironmentSet(ctx context.Context, in *EnvSetRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Release endpoints
	ReleaseList(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*ReleaseListResponse, error)
	ReleaseDelete(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ReleasePromote(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Resource endpoints
	ResourceList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ResourceListResponse, error)
	ResourceGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.Resource, error)
	ResourceCreate(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*models.Resource, error)
	ResourceDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ResourceLink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error)
	ResourceUnlink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error)
	// kubectl api wrappers
	Kubectl(ctx context.Context, in *KubectlReq, opts ...grpc.CallOption) (*CmdResponse, error)
	// Process api
	ProcessRun(ctx context.Context, opts ...grpc.CallOption) (ProviderService_ProcessRunClient, error)
	ProcessList(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*ProcessListResponse, error)
	ProcessSave(ctx context.Context, in *models.Formation, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ProcessLimits(ctx context.Context, in *models.ResourceLimits, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Logs API
	LogStream(ctx context.Context, in *LogStreamReq, opts ...grpc.CallOption) (ProviderService_LogStreamClient, error)
}

type providerServiceClient struct {
	cc *grpc.ClientConn
}

func NewProviderServiceClient(cc *grpc.ClientConn) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppCreate(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error) {
	out := new(models.App)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error) {
	out := new(models.App)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppRestart(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppRestart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) CertificateCreate(ctx context.Context, in *CertificateReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/CertificateCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) CertificateDelete(ctx context.Context, in *CertificateReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/CertificateDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppUpdateDomain(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppUpdateDomain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildCreate(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*models.Build, error) {
	out := new(models.Build)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildImport(ctx context.Context, opts ...grpc.CallOption) (ProviderService_BuildImportClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ProviderService_serviceDesc.Streams[0], c.cc, "/controller.ProviderService/BuildImport", opts...)
	if err != nil {
		return nil, err
	}
	x := &providerServiceBuildImportClient{stream}
	return x, nil
}

type ProviderService_BuildImportClient interface {
	Send(*StreamMsg) error
	CloseAndRecv() (*google_protobuf1.Empty, error)
	grpc.ClientStream
}

type providerServiceBuildImportClient struct {
	grpc.ClientStream
}

func (x *providerServiceBuildImportClient) Send(m *StreamMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *providerServiceBuildImportClient) CloseAndRecv() (*google_protobuf1.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf1.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *providerServiceClient) BuildRelease(ctx context.Context, in *CreateReleaseRequest, opts ...grpc.CallOption) (*models.Release, error) {
	out := new(models.Release)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildGet(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*models.Build, error) {
	out := new(models.Build)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildDelete(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildList(ctx context.Context, in *AppListRequest, opts ...grpc.CallOption) (*BuildListResponse, error) {
	out := new(BuildListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildLogs(ctx context.Context, in *BuildLogRequest, opts ...grpc.CallOption) (*BuildLogResponse, error) {
	out := new(BuildLogResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) EnvironmentGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.EnvConfig, error) {
	out := new(models.EnvConfig)
	err := grpc.Invoke(ctx, "/controller.ProviderService/EnvironmentGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) EnvironmentSet(ctx context.Context, in *EnvSetRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/EnvironmentSet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ReleaseList(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*ReleaseListResponse, error) {
	out := new(ReleaseListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ReleaseList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ReleaseDelete(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ReleaseDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ReleasePromote(ctx context.Context, in *AppIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ReleasePromote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ResourceListResponse, error) {
	out := new(ResourceListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceCreate(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceLink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceLink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceUnlink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceUnlink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) Kubectl(ctx context.Context, in *KubectlReq, opts ...grpc.CallOption) (*CmdResponse, error) {
	out := new(CmdResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/Kubectl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProcessRun(ctx context.Context, opts ...grpc.CallOption) (ProviderService_ProcessRunClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ProviderService_serviceDesc.Streams[1], c.cc, "/controller.ProviderService/ProcessRun", opts...)
	if err != nil {
		return nil, err
	}
	x := &providerServiceProcessRunClient{stream}
	return x, nil
}

type ProviderService_ProcessRunClient interface {
	Send(*StreamMsg) error
	Recv() (*StreamMsg, error)
	grpc.ClientStream
}

type providerServiceProcessRunClient struct {
	grpc.ClientStream
}

func (x *providerServiceProcessRunClient) Send(m *StreamMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *providerServiceProcessRunClient) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *providerServiceClient) ProcessList(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*ProcessListResponse, error) {
	out := new(ProcessListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ProcessList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProcessSave(ctx context.Context, in *models.Formation, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ProcessSave", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProcessLimits(ctx context.Context, in *models.ResourceLimits, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ProcessLimits", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) LogStream(ctx context.Context, in *LogStreamReq, opts ...grpc.CallOption) (ProviderService_LogStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ProviderService_serviceDesc.Streams[2], c.cc, "/controller.ProviderService/LogStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &providerServiceLogStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProviderService_LogStreamClient interface {
	Recv() (*StreamMsg, error)
	grpc.ClientStream
}

type providerServiceLogStreamClient struct {
	grpc.ClientStream
}

func (x *providerServiceLogStreamClient) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ProviderService service

type ProviderServiceServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	// Account api
	AppList(context.Context, *ListRequest) (*AppListResponse, error)
	AppCreate(context.Context, *AppRequest) (*models.App, error)
	AppGet(context.Context, *AppRequest) (*models.App, error)
	AppRestart(context.Context, *AppRequest) (*google_protobuf1.Empty, error)
	AppDelete(context.Context, *AppRequest) (*google_protobuf1.Empty, error)
	// Certificates API
	CertificateCreate(context.Context, *CertificateReq) (*google_protobuf1.Empty, error)
	CertificateDelete(context.Context, *CertificateReq) (*google_protobuf1.Empty, error)
	// Update Domain API
	AppUpdateDomain(context.Context, *AppResourceReq) (*google_protobuf1.Empty, error)
	// Build Api
	BuildCreate(context.Context, *CreateBuildRequest) (*models.Build, error)
	BuildImport(ProviderService_BuildImportServer) error
	BuildRelease(context.Context, *CreateReleaseRequest) (*models.Release, error)
	BuildGet(context.Context, *AppIdRequest) (*models.Build, error)
	BuildDelete(context.Context, *AppIdRequest) (*google_protobuf1.Empty, error)
	BuildList(context.Context, *AppListRequest) (*BuildListResponse, error)
	BuildLogs(context.Context, *BuildLogRequest) (*BuildLogResponse, error)
	EnvironmentGet(context.Context, *AppRequest) (*models.EnvConfig, error)
	EnvironmentSet(context.Context, *EnvSetRequest) (*google_protobuf1.Empty, error)
	// Release endpoints
	ReleaseList(context.Context, *AppRequest) (*ReleaseListResponse, error)
	ReleaseDelete(context.Context, *AppIdRequest) (*google_protobuf1.Empty, error)
	ReleasePromote(context.Context, *AppIdRequest) (*google_protobuf1.Empty, error)
	// Resource endpoints
	ResourceList(context.Context, *ListRequest) (*ResourceListResponse, error)
	ResourceGet(context.Context, *AppRequest) (*models.Resource, error)
	ResourceCreate(context.Context, *CreateResourceRequest) (*models.Resource, error)
	ResourceDelete(context.Context, *AppRequest) (*google_protobuf1.Empty, error)
	ResourceLink(context.Context, *AppResourceReq) (*models.Resource, error)
	ResourceUnlink(context.Context, *AppResourceReq) (*models.Resource, error)
	// kubectl api wrappers
	Kubectl(context.Context, *KubectlReq) (*CmdResponse, error)
	// Process api
	ProcessRun(ProviderService_ProcessRunServer) error
	ProcessList(context.Context, *AppRequest) (*ProcessListResponse, error)
	ProcessSave(context.Context, *models.Formation) (*google_protobuf1.Empty, error)
	ProcessLimits(context.Context, *models.ResourceLimits) (*google_protobuf1.Empty, error)
	// Logs API
	LogStream(*LogStreamReq, ProviderService_LogStreamServer) error
}

func RegisterProviderServiceServer(s *grpc.Server, srv ProviderServiceServer) {
	s.RegisterService(&_ProviderService_serviceDesc, srv)
}

func _ProviderService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppList(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppCreate(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppGet(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppRestart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppRestart(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppDelete(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_CertificateCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).CertificateCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/CertificateCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).CertificateCreate(ctx, req.(*CertificateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_CertificateDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).CertificateDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/CertificateDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).CertificateDelete(ctx, req.(*CertificateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppUpdateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppResourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppUpdateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppUpdateDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppUpdateDomain(ctx, req.(*AppResourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildCreate(ctx, req.(*CreateBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildImport_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServiceServer).BuildImport(&providerServiceBuildImportServer{stream})
}

type ProviderService_BuildImportServer interface {
	SendAndClose(*google_protobuf1.Empty) error
	Recv() (*StreamMsg, error)
	grpc.ServerStream
}

type providerServiceBuildImportServer struct {
	grpc.ServerStream
}

func (x *providerServiceBuildImportServer) SendAndClose(m *google_protobuf1.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *providerServiceBuildImportServer) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProviderService_BuildRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildRelease(ctx, req.(*CreateReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildGet(ctx, req.(*AppIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildDelete(ctx, req.(*AppIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildList(ctx, req.(*AppListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildLogs(ctx, req.(*BuildLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_EnvironmentGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).EnvironmentGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/EnvironmentGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).EnvironmentGet(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_EnvironmentSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).EnvironmentSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/EnvironmentSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).EnvironmentSet(ctx, req.(*EnvSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ReleaseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ReleaseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ReleaseList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ReleaseList(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ReleaseDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ReleaseDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ReleaseDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ReleaseDelete(ctx, req.(*AppIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ReleasePromote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ReleasePromote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ReleasePromote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ReleasePromote(ctx, req.(*AppIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceList(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceGet(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceCreate(ctx, req.(*CreateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceDelete(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppResourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceLink(ctx, req.(*AppResourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceUnlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppResourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceUnlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceUnlink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceUnlink(ctx, req.(*AppResourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_Kubectl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubectlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Kubectl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/Kubectl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Kubectl(ctx, req.(*KubectlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProcessRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServiceServer).ProcessRun(&providerServiceProcessRunServer{stream})
}

type ProviderService_ProcessRunServer interface {
	Send(*StreamMsg) error
	Recv() (*StreamMsg, error)
	grpc.ServerStream
}

type providerServiceProcessRunServer struct {
	grpc.ServerStream
}

func (x *providerServiceProcessRunServer) Send(m *StreamMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *providerServiceProcessRunServer) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProviderService_ProcessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProcessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ProcessList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProcessList(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProcessSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.Formation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProcessSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ProcessSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProcessSave(ctx, req.(*models.Formation))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProcessLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.ResourceLimits)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProcessLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ProcessLimits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProcessLimits(ctx, req.(*models.ResourceLimits))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_LogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogStreamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServiceServer).LogStream(m, &providerServiceLogStreamServer{stream})
}

type ProviderService_LogStreamServer interface {
	Send(*StreamMsg) error
	grpc.ServerStream
}

type providerServiceLogStreamServer struct {
	grpc.ServerStream
}

func (x *providerServiceLogStreamServer) Send(m *StreamMsg) error {
	return x.ServerStream.SendMsg(m)
}

var _ProviderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _ProviderService_Auth_Handler,
		},
		{
			MethodName: "AppList",
			Handler:    _ProviderService_AppList_Handler,
		},
		{
			MethodName: "AppCreate",
			Handler:    _ProviderService_AppCreate_Handler,
		},
		{
			MethodName: "AppGet",
			Handler:    _ProviderService_AppGet_Handler,
		},
		{
			MethodName: "AppRestart",
			Handler:    _ProviderService_AppRestart_Handler,
		},
		{
			MethodName: "AppDelete",
			Handler:    _ProviderService_AppDelete_Handler,
		},
		{
			MethodName: "CertificateCreate",
			Handler:    _ProviderService_CertificateCreate_Handler,
		},
		{
			MethodName: "CertificateDelete",
			Handler:    _ProviderService_CertificateDelete_Handler,
		},
		{
			MethodName: "AppUpdateDomain",
			Handler:    _ProviderService_AppUpdateDomain_Handler,
		},
		{
			MethodName: "BuildCreate",
			Handler:    _ProviderService_BuildCreate_Handler,
		},
		{
			MethodName: "BuildRelease",
			Handler:    _ProviderService_BuildRelease_Handler,
		},
		{
			MethodName: "BuildGet",
			Handler:    _ProviderService_BuildGet_Handler,
		},
		{
			MethodName: "BuildDelete",
			Handler:    _ProviderService_BuildDelete_Handler,
		},
		{
			MethodName: "BuildList",
			Handler:    _ProviderService_BuildList_Handler,
		},
		{
			MethodName: "BuildLogs",
			Handler:    _ProviderService_BuildLogs_Handler,
		},
		{
			MethodName: "EnvironmentGet",
			Handler:    _ProviderService_EnvironmentGet_Handler,
		},
		{
			MethodName: "EnvironmentSet",
			Handler:    _ProviderService_EnvironmentSet_Handler,
		},
		{
			MethodName: "ReleaseList",
			Handler:    _ProviderService_ReleaseList_Handler,
		},
		{
			MethodName: "ReleaseDelete",
			Handler:    _ProviderService_ReleaseDelete_Handler,
		},
		{
			MethodName: "ReleasePromote",
			Handler:    _ProviderService_ReleasePromote_Handler,
		},
		{
			MethodName: "ResourceList",
			Handler:    _ProviderService_ResourceList_Handler,
		},
		{
			MethodName: "ResourceGet",
			Handler:    _ProviderService_ResourceGet_Handler,
		},
		{
			MethodName: "ResourceCreate",
			Handler:    _ProviderService_ResourceCreate_Handler,
		},
		{
			MethodName: "ResourceDelete",
			Handler:    _ProviderService_ResourceDelete_Handler,
		},
		{
			MethodName: "ResourceLink",
			Handler:    _ProviderService_ResourceLink_Handler,
		},
		{
			MethodName: "ResourceUnlink",
			Handler:    _ProviderService_ResourceUnlink_Handler,
		},
		{
			MethodName: "Kubectl",
			Handler:    _ProviderService_Kubectl_Handler,
		},
		{
			MethodName: "ProcessList",
			Handler:    _ProviderService_ProcessList_Handler,
		},
		{
			MethodName: "ProcessSave",
			Handler:    _ProviderService_ProcessSave_Handler,
		},
		{
			MethodName: "ProcessLimits",
			Handler:    _ProviderService_ProcessLimits_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BuildImport",
			Handler:       _ProviderService_BuildImport_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ProcessRun",
			Handler:       _ProviderService_ProcessRun_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "LogStream",
			Handler:       _ProviderService_LogStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services.proto",
}

func init() { proto.RegisterFile("services.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x5b, 0x6f, 0x1c, 0x49,
	0x15, 0xa6, 0x1d, 0xdf, 0xe6, 0xcc, 0xf8, 0x56, 0xbe, 0x8d, 0x3b, 0x59, 0xdb, 0x5b, 0x4b, 0x20,
	0x78, 0x95, 0xe9, 0x10, 0x90, 0x00, 0x2f, 0x20, 0x39, 0xce, 0x04, 0x45, 0x18, 0xd6, 0xb4, 0x89,
	0x02, 0x64, 0x21, 0xdb, 0xee, 0xae, 0x99, 0x34, 0xee, 0xee, 0xaa, 0xad, 0xee, 0x99, 0xc5, 0x8a,
	0xc2, 0x03, 0x42, 0xe2, 0x07, 0xf0, 0x8b, 0x78, 0xdb, 0x47, 0x24, 0x5e, 0x11, 0x42, 0x11, 0x3f,
	0x04, 0x55, 0xd5, 0xa9, 0x76, 0xf7, 0x5c, 0x1c, 0xef, 0xee, 0xcb, 0xa8, 0x4f, 0xd5, 0xa9, 0xef,
	0x3b, 0x75, 0xea, 0x5c, 0xaa, 0x06, 0x96, 0x73, 0x26, 0x87, 0x71, 0xc8, 0xf2, 0x8e, 0x90, 0xbc,
	0xe0, 0x04, 0x42, 0x9e, 0x15, 0x92, 0x27, 0x09, 0x93, 0xee, 0x9d, 0x3e, 0xe7, 0xfd, 0x84, 0x79,
	0x81, 0x88, 0xbd, 0x20, 0xcb, 0x78, 0x11, 0x14, 0x31, 0xcf, 0x50, 0xd3, 0x6d, 0x8b, 0xe2, 0x52,
	0xb0, 0xdc, 0x63, 0xa9, 0x28, 0x2e, 0xcd, 0x2f, 0xce, 0xec, 0xe2, 0x4c, 0x34, 0x90, 0x7a, 0x45,
	0xf9, 0x81, 0xf3, 0xf7, 0xfb, 0x71, 0xf1, 0x6a, 0x70, 0xde, 0x09, 0x79, 0xea, 0xf5, 0x79, 0x9f,
	0x7b, 0x7a, 0xf8, 0x7c, 0xd0, 0xd3, 0x92, 0x16, 0xf4, 0x17, 0xaa, 0x7f, 0xbf, 0xa2, 0x1e, 0x05,
	0x45, 0x10, 0xf2, 0xe4, 0x7e, 0xcc, 0xed, 0xa7, 0xb6, 0x2e, 0xe5, 0x11, 0x4b, 0x72, 0x4f, 0xd3,
	0x9a, 0x55, 0xf4, 0x23, 0x68, 0x9e, 0xc4, 0x79, 0xe1, 0xb3, 0xcf, 0x06, 0x2c, 0x2f, 0xc8, 0x16,
	0xcc, 0xf3, 0x5e, 0x2f, 0x67, 0x45, 0xdb, 0xd9, 0x77, 0xee, 0xcd, 0xf9, 0x28, 0x91, 0x0d, 0x98,
	0x4b, 0xe2, 0x34, 0x2e, 0xda, 0x33, 0x7a, 0xd8, 0x08, 0xf4, 0x9b, 0xd0, 0x32, 0x8b, 0x73, 0xc1,
	0xb3, 0x9c, 0x29, 0xad, 0xb8, 0x60, 0x69, 0xde, 0x76, 0xf6, 0x6f, 0xdd, 0x6b, 0xf8, 0x46, 0xa0,
	0x1f, 0x01, 0x1c, 0x09, 0x61, 0x19, 0x08, 0xcc, 0x66, 0x41, 0xca, 0x34, 0x7e, 0xc3, 0xd7, 0xdf,
	0x64, 0x07, 0x16, 0x25, 0x13, 0xfc, 0xe5, 0x40, 0x26, 0x9a, 0xa0, 0xe1, 0x2f, 0x28, 0xf9, 0x99,
	0x4c, 0x68, 0x0f, 0x56, 0x8e, 0x84, 0xa8, 0xb1, 0xdc, 0x85, 0xd9, 0x40, 0x08, 0x43, 0xd2, 0x7c,
	0xd8, 0xec, 0x98, 0x5d, 0x75, 0x8e, 0x84, 0x78, 0x34, 0xfb, 0xc5, 0x7f, 0xf6, 0xbe, 0xe1, 0xeb,
	0xe9, 0xc9, 0x26, 0x57, 0x36, 0x78, 0xab, 0xba, 0x41, 0xfa, 0x1d, 0x68, 0x1e, 0x0d, 0x8a, 0x57,
	0xd6, 0x4a, 0x17, 0x16, 0x45, 0x90, 0xe7, 0x9f, 0x73, 0x19, 0xa1, 0xa5, 0xa5, 0x4c, 0xff, 0xea,
	0x40, 0xcb, 0xe8, 0xa2, 0x41, 0x04, 0x66, 0x5f, 0xf1, 0xbc, 0xb0, 0x5b, 0x52, 0xdf, 0xe5, 0x36,
	0x67, 0x2a, 0xdb, 0x6c, 0xc3, 0x82, 0x90, 0xfc, 0x8f, 0x2c, 0x34, 0xe4, 0x0d, 0xdf, 0x8a, 0xca,
	0x2a, 0xc9, 0xfa, 0x31, 0xcf, 0xda, 0xb3, 0x7a, 0x02, 0x25, 0x6d, 0x86, 0xe4, 0xc3, 0x38, 0x62,
	0xb2, 0x3d, 0x87, 0x66, 0xa0, 0x4c, 0x3f, 0x01, 0x72, 0x2c, 0x59, 0x50, 0xb0, 0x47, 0x83, 0x38,
	0x89, 0xac, 0xe1, 0xab, 0x70, 0x2b, 0x10, 0x02, 0x4d, 0x51, 0x9f, 0x8a, 0x75, 0xc8, 0x64, 0xae,
	0xc0, 0xd1, 0xb7, 0x28, 0x22, 0x7a, 0xd8, 0x8b, 0x13, 0xa6, 0x0d, 0x6a, 0xf9, 0xa5, 0x4c, 0x1f,
	0x40, 0xeb, 0x48, 0x88, 0xa7, 0xd7, 0xe0, 0x2e, 0xc3, 0x4c, 0x1c, 0x21, 0xe4, 0x4c, 0x1c, 0xd1,
	0x2e, 0xac, 0x68, 0x4b, 0x4e, 0x78, 0xff, 0xc6, 0x8b, 0x94, 0x86, 0xe0, 0x39, 0x9e, 0x85, 0xfa,
	0xa4, 0x87, 0xb0, 0x7a, 0x05, 0x83, 0x0e, 0x46, 0x2d, 0xa7, 0xd4, 0x32, 0x87, 0x9b, 0xb1, 0xbc,
	0x3d, 0x63, 0x22, 0x4d, 0x0b, 0xf4, 0x07, 0xb0, 0xd4, 0xcd, 0x86, 0x67, 0xac, 0xb8, 0x2e, 0xd8,
	0x08, 0xcc, 0xaa, 0x9c, 0xb0, 0x27, 0xa3, 0xbe, 0xe9, 0x13, 0xd8, 0xf0, 0x59, 0xce, 0x07, 0x32,
	0x64, 0xb5, 0x50, 0xeb, 0x40, 0x43, 0xe2, 0xb8, 0x8d, 0xb7, 0x55, 0x1b, 0x6f, 0x76, 0x81, 0x7f,
	0xa5, 0x42, 0x0f, 0x61, 0xb9, 0x8c, 0xd6, 0xe9, 0x16, 0x4c, 0x4e, 0xa6, 0x43, 0x58, 0x33, 0x1b,
	0xaf, 0xc7, 0xfa, 0xfc, 0xb9, 0x1a, 0xb4, 0xec, 0x4b, 0x96, 0xdd, 0x1c, 0x3a, 0x4e, 0xd2, 0x1f,
	0xc3, 0xfa, 0xa9, 0xe4, 0x21, 0xcb, 0xf3, 0x91, 0xd5, 0x73, 0x4f, 0xcb, 0x7c, 0x6c, 0x3e, 0x5c,
	0xb1, 0x8b, 0x51, 0xd7, 0x37, 0xb3, 0xf4, 0x1f, 0x0e, 0x6c, 0x9a, 0x50, 0x2a, 0xf7, 0x74, 0xbd,
	0xff, 0x2e, 0xe2, 0xcc, 0x1e, 0xa2, 0xfe, 0x26, 0x5d, 0x98, 0x17, 0x81, 0x0c, 0x52, 0x75, 0x92,
	0x8a, 0xe9, 0x7e, 0xe7, 0xaa, 0x3e, 0x76, 0x26, 0x42, 0x77, 0x4e, 0xb5, 0x7e, 0x37, 0x2b, 0xe4,
	0xa5, 0x8f, 0x8b, 0xdd, 0x1f, 0x41, 0xb3, 0x32, 0xac, 0x8e, 0xfd, 0x82, 0x5d, 0xda, 0xf0, 0xb9,
	0x60, 0x97, 0xca, 0x73, 0xc3, 0x20, 0x19, 0xd8, 0xb4, 0x32, 0xc2, 0xe1, 0xcc, 0x0f, 0x1d, 0xfa,
	0x53, 0xed, 0xf9, 0x0a, 0xc9, 0x84, 0xe0, 0x73, 0x55, 0x99, 0x31, 0x0a, 0x08, 0x50, 0xca, 0x74,
	0x1f, 0xe0, 0xe7, 0x83, 0x73, 0x16, 0x16, 0x89, 0x5a, 0x4b, 0x60, 0x36, 0x90, 0x7d, 0x5b, 0xc7,
	0xf4, 0x37, 0x4d, 0xa0, 0x79, 0x9c, 0x46, 0xa5, 0x6f, 0x6f, 0x43, 0x83, 0xfd, 0x29, 0x2e, 0x5e,
	0x86, 0x3c, 0x62, 0x18, 0x99, 0x8b, 0x6a, 0xe0, 0x98, 0x47, 0x3a, 0x60, 0x99, 0x94, 0x48, 0xa2,
	0x3e, 0x55, 0x86, 0xe7, 0x45, 0xf4, 0xf1, 0xc0, 0xa6, 0x3e, 0x4a, 0x38, 0xde, 0x95, 0xd2, 0x66,
	0xbe, 0x91, 0xe8, 0xdf, 0x1c, 0x68, 0x9d, 0xf0, 0xfe, 0x59, 0x21, 0x59, 0x90, 0xa2, 0x49, 0x63,
	0x47, 0xb1, 0x05, 0xf3, 0x3d, 0x9e, 0x24, 0xfc, 0x73, 0xcd, 0xb4, 0xe8, 0xa3, 0x44, 0x3c, 0x98,
	0xcb, 0xe3, 0x2c, 0x34, 0x59, 0xdd, 0x7c, 0xb8, 0xd3, 0x31, 0x1d, 0xaa, 0x63, 0x1b, 0x48, 0xe7,
	0x31, 0x76, 0x1a, 0xdf, 0xe8, 0xd9, 0x4a, 0xa0, 0x1a, 0x03, 0xda, 0x51, 0xca, 0xf4, 0x27, 0xb0,
	0x64, 0xe3, 0x65, 0x90, 0x4d, 0xb3, 0xa4, 0x0d, 0x0b, 0x21, 0x4f, 0xd3, 0x40, 0xc7, 0x85, 0xf2,
	0x99, 0x15, 0xe9, 0x1e, 0x34, 0xcc, 0x26, 0x7e, 0x91, 0xf7, 0xcb, 0xdc, 0x73, 0x74, 0xb5, 0x31,
	0xb9, 0xf7, 0x08, 0xd6, 0x7d, 0x96, 0xb0, 0x20, 0xaf, 0xa7, 0xde, 0x87, 0xea, 0xb0, 0xf4, 0xf0,
	0x58, 0xf8, 0xa2, 0xba, 0x5f, 0x2a, 0xd0, 0x33, 0xd8, 0xb0, 0x51, 0x66, 0xa6, 0x30, 0x7e, 0x3f,
	0x80, 0x39, 0x9d, 0x21, 0x9a, 0x70, 0x2c, 0x7b, 0xcc, 0x9c, 0xf2, 0x62, 0xc4, 0xd3, 0x20, 0xb6,
	0xf5, 0x11, 0x25, 0xfa, 0x2d, 0x20, 0xca, 0xa2, 0xc7, 0x5a, 0xf2, 0xd9, 0x67, 0x65, 0x2d, 0x52,
	0x6d, 0xca, 0x44, 0x86, 0xfa, 0xa4, 0x7f, 0x86, 0xe5, 0x63, 0x26, 0x8b, 0xb8, 0x17, 0x87, 0xda,
	0x82, 0x49, 0xa1, 0x37, 0x85, 0x83, 0xbc, 0x0f, 0xad, 0x90, 0xc9, 0xe2, 0x25, 0xcb, 0x54, 0x1c,
	0x45, 0x18, 0x1c, 0x4d, 0x35, 0xd6, 0x35, 0x43, 0x64, 0x0f, 0x9a, 0x17, 0xec, 0xb2, 0xd4, 0x30,
	0xc7, 0x03, 0x17, 0xec, 0x12, 0x15, 0x1e, 0xfe, 0x7b, 0x1b, 0x56, 0x4e, 0xb1, 0x2b, 0x9c, 0x99,
	0x6b, 0x0a, 0xf9, 0x25, 0xcc, 0xaa, 0x16, 0x45, 0xb6, 0xab, 0x89, 0x58, 0x69, 0x70, 0x6e, 0x7b,
	0x7c, 0xc2, 0x38, 0x9e, 0xae, 0xff, 0xe5, 0x5f, 0xff, 0xfb, 0xfb, 0xcc, 0x12, 0x5d, 0xf4, 0x86,
	0xdf, 0xf5, 0x82, 0x41, 0xf1, 0xea, 0xd0, 0x39, 0x20, 0xbf, 0x82, 0x05, 0x2c, 0x6c, 0x75, 0xc8,
	0x4a, 0xa9, 0x73, 0x6f, 0xd7, 0x20, 0xeb, 0x4d, 0x9b, 0xae, 0x6a, 0x54, 0x20, 0x06, 0x55, 0xf5,
	0xe7, 0x2e, 0x34, 0x8e, 0x84, 0x30, 0xc7, 0x46, 0xb6, 0x46, 0xd6, 0x5a, 0xcc, 0x6a, 0x77, 0x1f,
	0xb1, 0x4c, 0x88, 0x5c, 0x59, 0xf6, 0x04, 0xe6, 0x8f, 0x84, 0xf8, 0x19, 0x2b, 0x6e, 0x86, 0xb1,
	0xad, 0x31, 0xd6, 0xc8, 0x8a, 0xc5, 0xf0, 0x5e, 0xab, 0x00, 0x7e, 0x43, 0x7e, 0x8f, 0xb7, 0x94,
	0xbc, 0x08, 0xe4, 0x74, 0xac, 0xad, 0xb1, 0x54, 0xea, 0xaa, 0x1b, 0x1d, 0xdd, 0xd3, 0xb0, 0x3b,
	0x64, 0x7b, 0x04, 0xd6, 0x93, 0x08, 0xf8, 0x6b, 0xbd, 0xdb, 0xc7, 0x2c, 0x61, 0xd7, 0xec, 0x76,
	0x1a, 0x3a, 0x1a, 0x7d, 0x30, 0x66, 0xf4, 0xa7, 0xb0, 0x56, 0x09, 0x3d, 0xf4, 0xa5, 0x5b, 0x2b,
	0xbe, 0xb5, 0xc8, 0x7c, 0x17, 0x03, 0xd5, 0x0c, 0x2a, 0xfa, 0x72, 0xef, 0x75, 0x20, 0xc4, 0x28,
	0x03, 0xda, 0xff, 0x35, 0x18, 0x0e, 0x26, 0x30, 0xa8, 0x1b, 0xde, 0x33, 0x11, 0x29, 0x7c, 0x93,
	0x15, 0xee, 0x98, 0x7f, 0xca, 0xb2, 0x3e, 0x15, 0x7f, 0x47, 0xe3, 0xaf, 0xbb, 0x6b, 0x0a, 0xdf,
	0x64, 0x97, 0x65, 0x38, 0x85, 0xa6, 0x4e, 0x78, 0xf4, 0xcf, 0xee, 0x78, 0x73, 0xaa, 0x5e, 0xa1,
	0xdc, 0x7a, 0x95, 0xa0, 0x44, 0x03, 0xb7, 0x28, 0x28, 0x60, 0xd3, 0x6f, 0xc9, 0x6f, 0x11, 0xf1,
	0x69, 0x2a, 0xb8, 0x2c, 0xc8, 0x66, 0x15, 0xb1, 0xac, 0x76, 0xef, 0x32, 0x95, 0xae, 0x5d, 0x21,
	0x7a, 0xb1, 0x46, 0xba, 0xe7, 0x90, 0xe7, 0xd0, 0x42, 0x6b, 0x74, 0x25, 0x23, 0xfb, 0x93, 0x5a,
	0x69, 0xb5, 0xc8, 0xb9, 0xa3, 0x75, 0x91, 0x6e, 0x68, 0xfc, 0x65, 0xda, 0x52, 0xf8, 0xb6, 0x46,
	0x92, 0x13, 0x58, 0xd4, 0xc0, 0x2a, 0x55, 0xda, 0x23, 0x0e, 0x7e, 0x3a, 0x6d, 0xf3, 0xb5, 0x74,
	0x41, 0x53, 0x5f, 0xc7, 0xd1, 0x1b, 0xf2, 0x1b, 0xf4, 0x00, 0x46, 0xc4, 0x74, 0xc0, 0x1b, 0xc5,
	0x43, 0x15, 0x39, 0x80, 0x46, 0x79, 0x0f, 0x1a, 0x8b, 0x84, 0x6a, 0xbd, 0x79, 0xaf, 0x3a, 0x37,
	0x76, 0x75, 0xb2, 0x5e, 0x26, 0x55, 0x2f, 0x63, 0xda, 0x44, 0x96, 0x82, 0xf7, 0x73, 0x72, 0x7b,
	0x1c, 0xa6, 0xbc, 0xc1, 0xba, 0x77, 0x26, 0x4f, 0x22, 0xc5, 0x1d, 0x4d, 0xb1, 0x45, 0x36, 0x46,
	0xf6, 0xe0, 0x25, 0x0a, 0xf8, 0x0c, 0x96, 0xbb, 0xd9, 0x30, 0x96, 0x3c, 0x4b, 0x59, 0x56, 0x5c,
	0x57, 0xa1, 0xd6, 0xac, 0xd3, 0xbb, 0xd9, 0xf0, 0x98, 0x67, 0xbd, 0xb8, 0x4f, 0xb7, 0x34, 0xf4,
	0x2a, 0x59, 0x56, 0xd0, 0x2c, 0x1b, 0x5a, 0xd3, 0x5f, 0xd4, 0x40, 0xcf, 0x58, 0x41, 0x76, 0xaa,
	0xa0, 0xb5, 0xeb, 0xef, 0x54, 0xdf, 0x23, 0x38, 0x1d, 0x05, 0x0f, 0xa1, 0x59, 0x69, 0xc5, 0x53,
	0xcd, 0xdd, 0xab, 0x8e, 0x4f, 0xe8, 0xdd, 0xf4, 0xb6, 0xc6, 0xdf, 0x24, 0xeb, 0xd5, 0x00, 0xb4,
	0x24, 0xe7, 0xb0, 0x84, 0x6b, 0xbe, 0x72, 0xec, 0x60, 0xb5, 0x3d, 0xd8, 0xae, 0xe3, 0xab, 0x64,
	0x37, 0x31, 0x14, 0xc2, 0x32, 0x72, 0x9c, 0x4a, 0x9e, 0xf2, 0xaf, 0x43, 0x42, 0xa7, 0x92, 0x7c,
	0x0a, 0xad, 0xea, 0xa3, 0x61, 0x7a, 0x63, 0xdc, 0xaf, 0xfb, 0x6b, 0xfc, 0x9d, 0x41, 0x37, 0x35,
	0xd7, 0x0a, 0x59, 0x32, 0x5c, 0xf8, 0x9c, 0x20, 0xcf, 0xd4, 0x79, 0x18, 0xe1, 0xba, 0xf0, 0x19,
	0x7b, 0x92, 0xd4, 0x03, 0xb3, 0xc4, 0xb3, 0x27, 0xf0, 0x89, 0xf2, 0x8e, 0x19, 0xc3, 0x92, 0xf8,
	0xfe, 0x3b, 0xef, 0xeb, 0x13, 0x48, 0xd0, 0x68, 0x3a, 0x62, 0xf4, 0x1f, 0xae, 0xd0, 0xbf, 0x62,
	0xbb, 0x43, 0xeb, 0x0f, 0x26, 0x5b, 0x1f, 0x57, 0xdd, 0x9e, 0x5d, 0x5c, 0xdb, 0x2c, 0xc6, 0x8d,
	0xfe, 0x50, 0x63, 0xdf, 0x75, 0x3f, 0x18, 0xc1, 0xd6, 0xc7, 0x9a, 0xc4, 0xd9, 0x85, 0xf7, 0xda,
	0x8e, 0xbe, 0x21, 0xe9, 0xd5, 0x56, 0x9e, 0x65, 0xc9, 0x97, 0x27, 0xbb, 0xaf, 0xc9, 0xbe, 0xed,
	0xde, 0x9d, 0x44, 0x36, 0xc8, 0x46, 0xe9, 0x3e, 0x86, 0x05, 0x7c, 0x83, 0xd4, 0x5d, 0x76, 0xf5,
	0x30, 0x71, 0x6b, 0x31, 0x56, 0x79, 0x8e, 0xd8, 0xbb, 0x11, 0x69, 0x2a, 0xaa, 0x0b, 0x44, 0x79,
	0x0e, 0x70, 0x75, 0x75, 0x9f, 0xd6, 0xa5, 0x26, 0x0f, 0xd7, 0x2b, 0xbf, 0x30, 0x28, 0x9e, 0x1c,
	0x64, 0xf7, 0x9c, 0x07, 0x0e, 0x79, 0x01, 0xcd, 0xca, 0x7b, 0xf3, 0x66, 0x85, 0x62, 0xc2, 0x03,
	0xb5, 0x6e, 0x35, 0x92, 0x90, 0xe7, 0x25, 0xf8, 0x59, 0x30, 0x64, 0xa4, 0x2c, 0x8e, 0x4f, 0xb8,
	0x4c, 0xf5, 0xab, 0x65, 0x6a, 0xe0, 0xbc, 0xa7, 0xe1, 0xb6, 0xc9, 0x66, 0xd5, 0xe6, 0x9e, 0x5d,
	0x46, 0x5e, 0x94, 0x2f, 0x99, 0x13, 0xf5, 0xe2, 0xce, 0xc9, 0xd6, 0xe8, 0x89, 0x99, 0xf1, 0xa9,
	0xf8, 0xae, 0xc6, 0xdf, 0x70, 0x49, 0x15, 0x3f, 0x31, 0x58, 0xcf, 0xa1, 0x51, 0xbe, 0xd7, 0xea,
	0xd5, 0xa6, 0xfa, 0x8c, 0xbb, 0x91, 0xb7, 0x55, 0xf7, 0xc0, 0x68, 0x7f, 0xe0, 0x3c, 0x6a, 0x7f,
	0xf1, 0x76, 0xd7, 0xf9, 0xe7, 0xdb, 0x5d, 0xe7, 0xbf, 0x6f, 0x77, 0x9d, 0xdf, 0x55, 0xfe, 0x78,
	0x3c, 0x9f, 0xd7, 0xe6, 0x7d, 0xef, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x99, 0x8e, 0x23, 0xab,
	0x9d, 0x14, 0x00, 0x00,
}
