// Code generated by protoc-gen-go.
// source: services.proto
// DO NOT EDIT!

/*
Package controller is a generated protocol buffer package.

It is generated from these files:
	services.proto

It has these top-level messages:
	ListRequest
	AppRequest
	AppListResponse
	AuthRequest
	AuthResponse
	CreateBuildRequest
	GetBuildRequest
	BuildLogRequest
	BuildLogResponse
	EnvSetRequest
	ResourceListResponse
	CreateResourceRequest
	AppResourceReq
*/
package controller

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/gogo/protobuf/gogoproto"
import models "github.com/dinesh/datacol/api/models"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRequest struct {
	Offset int32 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type AppRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *AppRequest) Reset()                    { *m = AppRequest{} }
func (m *AppRequest) String() string            { return proto.CompactTextString(m) }
func (*AppRequest) ProtoMessage()               {}
func (*AppRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AppListResponse struct {
	Apps   []*models.App `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
	Limit  int32         `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset int32         `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *AppListResponse) Reset()                    { *m = AppListResponse{} }
func (m *AppListResponse) String() string            { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()               {}
func (*AppListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppListResponse) GetApps() []*models.App {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *AppListResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AppListResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type AuthRequest struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Host    string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Project string `protobuf:"bytes,3,opt,name=project" json:"project,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AuthResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AuthResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuthResponse) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type CreateBuildRequest struct {
	App  string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *CreateBuildRequest) Reset()                    { *m = CreateBuildRequest{} }
func (m *CreateBuildRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBuildRequest) ProtoMessage()               {}
func (*CreateBuildRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateBuildRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *CreateBuildRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBuildRequest struct {
	App string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *GetBuildRequest) Reset()                    { *m = GetBuildRequest{} }
func (m *GetBuildRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBuildRequest) ProtoMessage()               {}
func (*GetBuildRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetBuildRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *GetBuildRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BuildLogRequest struct {
	App string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Pos int32  `protobuf:"varint,3,opt,name=pos" json:"pos,omitempty"`
}

func (m *BuildLogRequest) Reset()                    { *m = BuildLogRequest{} }
func (m *BuildLogRequest) String() string            { return proto.CompactTextString(m) }
func (*BuildLogRequest) ProtoMessage()               {}
func (*BuildLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BuildLogRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *BuildLogRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BuildLogRequest) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type BuildLogResponse struct {
	Pos   int32    `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	Lines []string `protobuf:"bytes,2,rep,name=lines" json:"lines,omitempty"`
}

func (m *BuildLogResponse) Reset()                    { *m = BuildLogResponse{} }
func (m *BuildLogResponse) String() string            { return proto.CompactTextString(m) }
func (*BuildLogResponse) ProtoMessage()               {}
func (*BuildLogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BuildLogResponse) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *BuildLogResponse) GetLines() []string {
	if m != nil {
		return m.Lines
	}
	return nil
}

type EnvSetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *EnvSetRequest) Reset()                    { *m = EnvSetRequest{} }
func (m *EnvSetRequest) String() string            { return proto.CompactTextString(m) }
func (*EnvSetRequest) ProtoMessage()               {}
func (*EnvSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EnvSetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnvSetRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ResourceListResponse struct {
	Resources []*models.Resource `protobuf:"bytes,1,rep,name=resources" json:"resources,omitempty"`
}

func (m *ResourceListResponse) Reset()                    { *m = ResourceListResponse{} }
func (m *ResourceListResponse) String() string            { return proto.CompactTextString(m) }
func (*ResourceListResponse) ProtoMessage()               {}
func (*ResourceListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ResourceListResponse) GetResources() []*models.Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type CreateResourceRequest struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Kind   string            `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Params map[string]string `protobuf:"bytes,3,rep,name=params" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CreateResourceRequest) Reset()                    { *m = CreateResourceRequest{} }
func (m *CreateResourceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateResourceRequest) ProtoMessage()               {}
func (*CreateResourceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateResourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateResourceRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *CreateResourceRequest) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type AppResourceReq struct {
	App  string `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *AppResourceReq) Reset()                    { *m = AppResourceReq{} }
func (m *AppResourceReq) String() string            { return proto.CompactTextString(m) }
func (*AppResourceReq) ProtoMessage()               {}
func (*AppResourceReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AppResourceReq) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *AppResourceReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "controller.ListRequest")
	proto.RegisterType((*AppRequest)(nil), "controller.AppRequest")
	proto.RegisterType((*AppListResponse)(nil), "controller.AppListResponse")
	proto.RegisterType((*AuthRequest)(nil), "controller.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "controller.AuthResponse")
	proto.RegisterType((*CreateBuildRequest)(nil), "controller.CreateBuildRequest")
	proto.RegisterType((*GetBuildRequest)(nil), "controller.GetBuildRequest")
	proto.RegisterType((*BuildLogRequest)(nil), "controller.BuildLogRequest")
	proto.RegisterType((*BuildLogResponse)(nil), "controller.BuildLogResponse")
	proto.RegisterType((*EnvSetRequest)(nil), "controller.EnvSetRequest")
	proto.RegisterType((*ResourceListResponse)(nil), "controller.ResourceListResponse")
	proto.RegisterType((*CreateResourceRequest)(nil), "controller.CreateResourceRequest")
	proto.RegisterType((*AppResourceReq)(nil), "controller.AppResourceReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProviderService service

type ProviderServiceClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Account api
	AppList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*AppListResponse, error)
	AppCreate(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error)
	AppGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error)
	AppRestart(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	AppDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Build Api
	BuildCreate(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*models.Build, error)
	BuildRelease(ctx context.Context, in *models.Build, opts ...grpc.CallOption) (*models.Release, error)
	BuildGet(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*models.Build, error)
	BuildLogs(ctx context.Context, in *BuildLogRequest, opts ...grpc.CallOption) (*BuildLogResponse, error)
	EnvironmentGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.EnvConfig, error)
	EnvironmentSet(ctx context.Context, in *EnvSetRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Resource endpoints
	ResourceList(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ResourceListResponse, error)
	ResourceGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.Resource, error)
	ResourceCreate(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*models.Resource, error)
	ResourceDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ResourceLink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error)
	ResourceUnlink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error)
}

type providerServiceClient struct {
	cc *grpc.ClientConn
}

func NewProviderServiceClient(cc *grpc.ClientConn) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppCreate(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error) {
	out := new(models.App)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.App, error) {
	out := new(models.App)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppRestart(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppRestart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) AppDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/AppDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildCreate(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*models.Build, error) {
	out := new(models.Build)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildRelease(ctx context.Context, in *models.Build, opts ...grpc.CallOption) (*models.Release, error) {
	out := new(models.Release)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildGet(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*models.Build, error) {
	out := new(models.Build)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) BuildLogs(ctx context.Context, in *BuildLogRequest, opts ...grpc.CallOption) (*BuildLogResponse, error) {
	out := new(BuildLogResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/BuildLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) EnvironmentGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.EnvConfig, error) {
	out := new(models.EnvConfig)
	err := grpc.Invoke(ctx, "/controller.ProviderService/EnvironmentGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) EnvironmentSet(ctx context.Context, in *EnvSetRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/EnvironmentSet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceList(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ResourceListResponse, error) {
	out := new(ResourceListResponse)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceGet(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceCreate(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceDelete(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceLink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceLink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ResourceUnlink(ctx context.Context, in *AppResourceReq, opts ...grpc.CallOption) (*models.Resource, error) {
	out := new(models.Resource)
	err := grpc.Invoke(ctx, "/controller.ProviderService/ResourceUnlink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProviderService service

type ProviderServiceServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	// Account api
	AppList(context.Context, *ListRequest) (*AppListResponse, error)
	AppCreate(context.Context, *AppRequest) (*models.App, error)
	AppGet(context.Context, *AppRequest) (*models.App, error)
	AppRestart(context.Context, *AppRequest) (*google_protobuf1.Empty, error)
	AppDelete(context.Context, *AppRequest) (*google_protobuf1.Empty, error)
	// Build Api
	BuildCreate(context.Context, *CreateBuildRequest) (*models.Build, error)
	BuildRelease(context.Context, *models.Build) (*models.Release, error)
	BuildGet(context.Context, *GetBuildRequest) (*models.Build, error)
	BuildLogs(context.Context, *BuildLogRequest) (*BuildLogResponse, error)
	EnvironmentGet(context.Context, *AppRequest) (*models.EnvConfig, error)
	EnvironmentSet(context.Context, *EnvSetRequest) (*google_protobuf1.Empty, error)
	// Resource endpoints
	ResourceList(context.Context, *google_protobuf1.Empty) (*ResourceListResponse, error)
	ResourceGet(context.Context, *AppRequest) (*models.Resource, error)
	ResourceCreate(context.Context, *CreateResourceRequest) (*models.Resource, error)
	ResourceDelete(context.Context, *AppRequest) (*google_protobuf1.Empty, error)
	ResourceLink(context.Context, *AppResourceReq) (*models.Resource, error)
	ResourceUnlink(context.Context, *AppResourceReq) (*models.Resource, error)
}

func RegisterProviderServiceServer(s *grpc.Server, srv ProviderServiceServer) {
	s.RegisterService(&_ProviderService_serviceDesc, srv)
}

func _ProviderService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppList(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppCreate(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppGet(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppRestart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppRestart(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_AppDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).AppDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/AppDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).AppDelete(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildCreate(ctx, req.(*CreateBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.Build)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildRelease(ctx, req.(*models.Build))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildGet(ctx, req.(*GetBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_BuildLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).BuildLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/BuildLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).BuildLogs(ctx, req.(*BuildLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_EnvironmentGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).EnvironmentGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/EnvironmentGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).EnvironmentGet(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_EnvironmentSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).EnvironmentSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/EnvironmentSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).EnvironmentSet(ctx, req.(*EnvSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceList(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceGet(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceCreate(ctx, req.(*CreateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceDelete(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppResourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceLink(ctx, req.(*AppResourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ResourceUnlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppResourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ResourceUnlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ProviderService/ResourceUnlink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ResourceUnlink(ctx, req.(*AppResourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProviderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _ProviderService_Auth_Handler,
		},
		{
			MethodName: "AppList",
			Handler:    _ProviderService_AppList_Handler,
		},
		{
			MethodName: "AppCreate",
			Handler:    _ProviderService_AppCreate_Handler,
		},
		{
			MethodName: "AppGet",
			Handler:    _ProviderService_AppGet_Handler,
		},
		{
			MethodName: "AppRestart",
			Handler:    _ProviderService_AppRestart_Handler,
		},
		{
			MethodName: "AppDelete",
			Handler:    _ProviderService_AppDelete_Handler,
		},
		{
			MethodName: "BuildCreate",
			Handler:    _ProviderService_BuildCreate_Handler,
		},
		{
			MethodName: "BuildRelease",
			Handler:    _ProviderService_BuildRelease_Handler,
		},
		{
			MethodName: "BuildGet",
			Handler:    _ProviderService_BuildGet_Handler,
		},
		{
			MethodName: "BuildLogs",
			Handler:    _ProviderService_BuildLogs_Handler,
		},
		{
			MethodName: "EnvironmentGet",
			Handler:    _ProviderService_EnvironmentGet_Handler,
		},
		{
			MethodName: "EnvironmentSet",
			Handler:    _ProviderService_EnvironmentSet_Handler,
		},
		{
			MethodName: "ResourceList",
			Handler:    _ProviderService_ResourceList_Handler,
		},
		{
			MethodName: "ResourceGet",
			Handler:    _ProviderService_ResourceGet_Handler,
		},
		{
			MethodName: "ResourceCreate",
			Handler:    _ProviderService_ResourceCreate_Handler,
		},
		{
			MethodName: "ResourceDelete",
			Handler:    _ProviderService_ResourceDelete_Handler,
		},
		{
			MethodName: "ResourceLink",
			Handler:    _ProviderService_ResourceLink_Handler,
		},
		{
			MethodName: "ResourceUnlink",
			Handler:    _ProviderService_ResourceUnlink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}

func init() { proto.RegisterFile("services.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1030 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x96, 0x4b, 0x6f, 0x1b, 0x37,
	0x10, 0xc7, 0xbb, 0xb2, 0xe3, 0x58, 0x23, 0x59, 0x72, 0x18, 0x3f, 0x94, 0xb5, 0xe1, 0x07, 0x8b,
	0xa2, 0x8e, 0x81, 0xec, 0xb6, 0x09, 0xd0, 0x87, 0x7b, 0x92, 0x13, 0x25, 0x97, 0xa0, 0x75, 0xd7,
	0xcd, 0xa5, 0x4f, 0xac, 0x25, 0x5a, 0xde, 0x7a, 0x45, 0xb2, 0x4b, 0x4a, 0x85, 0x61, 0xf8, 0xd2,
	0xaf, 0xd0, 0x2f, 0xd4, 0xde, 0x72, 0x2c, 0xd0, 0x7b, 0x51, 0x18, 0xfd, 0x20, 0x05, 0xb9, 0xa4,
	0xf6, 0xe1, 0xb5, 0x92, 0xf6, 0x46, 0x2e, 0x67, 0x7e, 0xf3, 0xe7, 0x70, 0x66, 0xb0, 0xd0, 0x12,
	0x24, 0x99, 0x44, 0x7d, 0x22, 0x3c, 0x9e, 0x30, 0xc9, 0x10, 0xf4, 0x19, 0x95, 0x09, 0x8b, 0x63,
	0x92, 0xb8, 0x9b, 0x43, 0xc6, 0x86, 0x31, 0xf1, 0x43, 0x1e, 0xf9, 0x21, 0xa5, 0x4c, 0x86, 0x32,
	0x62, 0xd4, 0x58, 0xba, 0x1b, 0xe6, 0x54, 0xef, 0x4e, 0xc6, 0xa7, 0x3e, 0x19, 0x71, 0x79, 0x61,
	0x0e, 0x1f, 0x0d, 0x23, 0x79, 0x36, 0x3e, 0xf1, 0xfa, 0x6c, 0xe4, 0x0f, 0xd9, 0x90, 0x65, 0x56,
	0x6a, 0xa7, 0x37, 0x7a, 0x65, 0xcc, 0x3f, 0xc8, 0x99, 0x0f, 0x22, 0x4a, 0xc4, 0x99, 0x3f, 0x08,
	0x65, 0xd8, 0x67, 0xb1, 0x0e, 0x3e, 0x62, 0x03, 0x12, 0x0b, 0x5f, 0x5e, 0x70, 0xab, 0x13, 0x7f,
	0x06, 0x8d, 0x97, 0x91, 0x90, 0x01, 0xf9, 0x69, 0x4c, 0x84, 0x44, 0x6b, 0xb0, 0xc0, 0x4e, 0x4f,
	0x05, 0x91, 0x1d, 0x67, 0xc7, 0xd9, 0xbb, 0x13, 0x98, 0x1d, 0x5a, 0x81, 0x3b, 0x71, 0x34, 0x8a,
	0x64, 0xa7, 0xa6, 0x3f, 0xa7, 0x1b, 0xbc, 0x03, 0xd0, 0xe5, 0xdc, 0xfa, 0x22, 0x98, 0xa7, 0xe1,
	0x88, 0x68, 0xcf, 0x7a, 0xa0, 0xd7, 0xf8, 0x14, 0xda, 0x5d, 0xce, 0xd3, 0x08, 0x82, 0x33, 0x2a,
	0x08, 0x7a, 0x0f, 0xe6, 0x43, 0xce, 0x45, 0xc7, 0xd9, 0x99, 0xdb, 0x6b, 0x3c, 0x6e, 0x78, 0xa9,
	0x28, 0xaf, 0xcb, 0xf9, 0xe1, 0xfc, 0xeb, 0xbf, 0xb6, 0xdf, 0x09, 0xf4, 0x71, 0x75, 0xc4, 0x9c,
	0xbe, 0xb9, 0xbc, 0x3e, 0xfc, 0x10, 0x1a, 0xdd, 0xb1, 0x3c, 0xb3, 0x52, 0x5c, 0x58, 0xe4, 0xa1,
	0x10, 0x3f, 0xb3, 0x64, 0x60, 0xe4, 0x4c, 0xf7, 0xf8, 0x08, 0x9a, 0xa9, 0xa9, 0xd1, 0x83, 0x60,
	0xfe, 0x8c, 0x09, 0x69, 0x65, 0xab, 0xf5, 0xf4, 0x2a, 0xb5, 0xec, 0x2a, 0xa8, 0x03, 0x77, 0x79,
	0xc2, 0x7e, 0x24, 0xfd, 0x34, 0x76, 0x3d, 0xb0, 0x5b, 0x7c, 0x00, 0xe8, 0x69, 0x42, 0x42, 0x49,
	0x0e, 0xc7, 0x51, 0x3c, 0xb0, 0x1a, 0x96, 0x61, 0x2e, 0xe4, 0xdc, 0x60, 0xd5, 0x52, 0x51, 0xd5,
	0x6b, 0x68, 0x6a, 0x33, 0xd0, 0x6b, 0xfc, 0x04, 0xda, 0x2f, 0x88, 0x7c, 0x83, 0x63, 0x0b, 0x6a,
	0xd1, 0xc0, 0x88, 0xa9, 0x45, 0x03, 0xdc, 0x83, 0xb6, 0xf6, 0x78, 0xc9, 0x86, 0x6f, 0xed, 0xa4,
	0x2c, 0x38, 0x13, 0x26, 0x6f, 0x6a, 0x89, 0x0f, 0x60, 0x39, 0xc3, 0x98, 0x6c, 0x18, 0x2b, 0x67,
	0x6a, 0x95, 0x3e, 0x04, 0x25, 0xa2, 0x53, 0xdb, 0x99, 0xdb, 0xab, 0x07, 0xe9, 0x06, 0x7f, 0x0c,
	0x4b, 0x3d, 0x3a, 0x39, 0x26, 0x72, 0xc6, 0xeb, 0x17, 0x2e, 0x5c, 0x37, 0x17, 0x7e, 0x0e, 0x2b,
	0x01, 0x11, 0x6c, 0x9c, 0xf4, 0x49, 0xa1, 0x2c, 0x3c, 0xa8, 0x27, 0xe6, 0xbb, 0xad, 0x8d, 0x65,
	0x5b, 0x1b, 0xd6, 0x21, 0xc8, 0x4c, 0xf0, 0xef, 0x0e, 0xac, 0xa6, 0x59, 0x9f, 0x9e, 0xce, 0x56,
	0x72, 0x1e, 0x51, 0x9b, 0x0e, 0xbd, 0x46, 0x3d, 0x58, 0xe0, 0x61, 0x12, 0x8e, 0x54, 0x4e, 0x54,
	0xb8, 0x47, 0x5e, 0xd6, 0xb3, 0x5e, 0x25, 0xda, 0x3b, 0xd2, 0xf6, 0x3d, 0x2a, 0x93, 0x8b, 0xc0,
	0x38, 0xbb, 0x9f, 0x42, 0x23, 0xf7, 0x59, 0x25, 0xf0, 0x9c, 0x5c, 0xd8, 0x87, 0x38, 0x27, 0x17,
	0x2a, 0x81, 0x93, 0x30, 0x1e, 0xdb, 0x6a, 0x4a, 0x37, 0x07, 0xb5, 0x4f, 0x1c, 0xfc, 0x11, 0xb4,
	0x74, 0xff, 0x4c, 0x83, 0x54, 0x17, 0x4d, 0xb9, 0x14, 0x1f, 0xff, 0xd6, 0x84, 0xf6, 0x51, 0xc2,
	0x26, 0xd1, 0x80, 0x24, 0xc7, 0xe9, 0xdc, 0x41, 0x9f, 0xc3, 0xbc, 0x2a, 0x6b, 0xb4, 0x9e, 0xbf,
	0x45, 0xae, 0x27, 0xdc, 0xce, 0xcd, 0x83, 0x34, 0xf5, 0xf8, 0xfe, 0x2f, 0x7f, 0xfe, 0xf3, 0x6b,
	0x6d, 0x09, 0x2f, 0xfa, 0x93, 0x0f, 0xfd, 0x70, 0x2c, 0xcf, 0x0e, 0x9c, 0x7d, 0xf4, 0x25, 0xdc,
	0x35, 0x9d, 0x5b, 0x44, 0xe6, 0xa6, 0x85, 0xbb, 0x51, 0x40, 0x16, 0xfb, 0x1c, 0x2f, 0x6b, 0x2a,
	0xa0, 0x94, 0xaa, 0x5a, 0xba, 0x07, 0xf5, 0x2e, 0xe7, 0x69, 0x66, 0xd1, 0x5a, 0xc9, 0xd7, 0x32,
	0xf3, 0x03, 0xa1, 0xa4, 0x8c, 0x73, 0xa1, 0x94, 0x3d, 0x87, 0x85, 0x2e, 0xe7, 0x2f, 0x88, 0x7c,
	0x3b, 0xc6, 0xba, 0x66, 0xdc, 0x43, 0x6d, 0xcb, 0xf0, 0x2f, 0x55, 0x12, 0xaf, 0xd0, 0x77, 0x66,
	0x7a, 0x09, 0x19, 0x26, 0xb7, 0xb3, 0xd6, 0xbc, 0x74, 0x3e, 0x7b, 0x76, 0xf2, 0x7a, 0x3d, 0x35,
	0x9f, 0xf1, 0xb6, 0xc6, 0x3e, 0x40, 0xeb, 0x25, 0xac, 0x9f, 0x18, 0xe0, 0x57, 0xfa, 0xb6, 0xcf,
	0x48, 0x4c, 0x66, 0xdc, 0xf6, 0x36, 0xba, 0x11, 0xbd, 0x7f, 0x43, 0xf4, 0x11, 0x34, 0x74, 0xcf,
	0x9a, 0x2c, 0x6e, 0xdd, 0xac, 0xd9, 0xfc, 0x2c, 0x71, 0x97, 0x6c, 0x26, 0xf4, 0x57, 0x8c, 0x34,
	0xb6, 0x89, 0x41, 0x61, 0x4f, 0xd4, 0x27, 0x81, 0x9e, 0x41, 0xd3, 0xb8, 0xc4, 0x24, 0x14, 0x04,
	0x15, 0x5d, 0xdc, 0x76, 0xd6, 0x84, 0xfa, 0x1c, 0xaf, 0x68, 0x46, 0x0b, 0x37, 0x15, 0x23, 0x49,
	0x3f, 0x0a, 0xf4, 0x05, 0x2c, 0x6a, 0x7b, 0xf5, 0x2c, 0x85, 0xb2, 0x28, 0x4d, 0xb7, 0xb2, 0x22,
	0x73, 0x51, 0xdc, 0xce, 0x14, 0xf9, 0x97, 0xd1, 0xe0, 0x0a, 0xf5, 0xa1, 0x6e, 0x87, 0x93, 0x28,
	0x12, 0x4b, 0xa3, 0xcf, 0xdd, 0xac, 0x3e, 0x34, 0x65, 0xb8, 0xa1, 0x03, 0xac, 0xe2, 0xfb, 0xa5,
	0x00, 0x7e, 0xcc, 0x86, 0xe8, 0x18, 0x5a, 0x3d, 0x3a, 0x89, 0x12, 0x46, 0x47, 0x84, 0xca, 0x59,
	0x25, 0x75, 0xcf, 0xca, 0xee, 0xd1, 0xc9, 0x53, 0x46, 0x4f, 0xa3, 0x21, 0x5e, 0xd3, 0xe4, 0x65,
	0xd4, 0x52, 0x64, 0x42, 0x27, 0xf6, 0x89, 0xbe, 0x29, 0x40, 0x8f, 0x89, 0x44, 0x0f, 0xf2, 0xd0,
	0xc2, 0xd8, 0xbc, 0xb5, 0x00, 0x0c, 0x1c, 0x97, 0xe1, 0x3f, 0x40, 0x33, 0x3f, 0x3e, 0xd1, 0x2d,
	0xfe, 0xee, 0x4e, 0x3e, 0x64, 0xd5, 0xc0, 0xc5, 0xab, 0x3a, 0x42, 0x1b, 0x2d, 0xa5, 0xef, 0x68,
	0xe6, 0x2a, 0x7a, 0x05, 0x0d, 0x6b, 0x3e, 0x2b, 0x1f, 0x37, 0x66, 0x33, 0xde, 0xd4, 0xbc, 0x35,
	0xbc, 0x52, 0xe0, 0x59, 0xdd, 0xdf, 0x42, 0xcb, 0x5a, 0x9a, 0xd2, 0xdd, 0x7d, 0xe3, 0xb8, 0xad,
	0x08, 0x62, 0x44, 0xe3, 0x92, 0xe8, 0xef, 0x33, 0xfa, 0xff, 0x6c, 0x38, 0xa3, 0x7e, 0xbf, 0x5a,
	0x3d, 0xc9, 0x67, 0x9d, 0x9e, 0x23, 0xf7, 0x06, 0x7d, 0x2a, 0xbc, 0x42, 0xf4, 0xfb, 0x9a, 0xbd,
	0xeb, 0x6e, 0x57, 0xb1, 0xfd, 0x38, 0xa2, 0xe7, 0xfe, 0x65, 0xc8, 0xf9, 0x15, 0x8a, 0xb2, 0x6b,
	0xbc, 0xa2, 0xf1, 0x7f, 0x0f, 0xf4, 0x50, 0x07, 0x7a, 0xd7, 0xdd, 0xad, 0x0c, 0x34, 0xa6, 0x59,
	0xa8, 0xc3, 0xce, 0xeb, 0xeb, 0x2d, 0xe7, 0x8f, 0xeb, 0x2d, 0xe7, 0xef, 0xeb, 0x2d, 0xe7, 0xeb,
	0xdc, 0xdf, 0xea, 0xc9, 0x82, 0xce, 0xcc, 0x93, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x45,
	0x22, 0xb6, 0xd2, 0x0a, 0x00, 0x00,
}
